### ISSUE TITLE
[TCOTD2] Cheesing out the hellhound mini-boss fight

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#100]
Currently, there is a way to kill two of the hellhounds in the barn before even triggering the encounter proper: if you stand all the way to the left of the entrance (without stepping into the barn) and turn right towards the direction where the dogs are, you'll be able to see and kill two of them from your position without any of them being able to do much (they can breath fire, but you're out of range). They can't come after you since they're blocked by some of the things in the barn as well as the third dog.

**Comment by nashmuhandes** [comment]
Should largely be resolved now with the cutscene system in place. The cutscene will trigger from a line way before you could ever get a drop on them. I've also set them to be dormant at map start, and scripted their activation, for good measure
