### ISSUE TITLE
[TCOTD2] Support the alternate HUD

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#102]
Currently the alt. HUD doesn't show the oil meter, as well as the pendant. I believe there are some convenient virtuals that could be used to override the drawing.

I don't have much experience (or at all) working with the alt HUD but if someone else (Blue Shadow?) would like to take a crack at it, you'd be more than welcome

**Comment by Tormentor667** [comment]
I am okay with it but I have to say that I am not fond with all that HUD stuff as well.

**Comment by Blue-Shadow** [comment]
Never worked on the alt HUD before, but I'll see what I can do.

**Comment by nashmuhandes** [comment]
Yeah looks dope!

**Comment by Blue-Shadow** [comment]
Pushed the changes.
