### ISSUE TITLE
[TCOTD2] Hint at the player the need to discover the solution to the church puzzle before attempting to solve it

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#103]
Since it is now a requirement to discover the solution in order to solve the puzzle in the church, there's no need to go to the church once the player gets the fire key while yet to discover the solution to the puzzle. Since in that case, all attempts to solve the puzzle are futile, and will result in instant death.

There needs to be something to hint at the player that he or she needs to do something else, first, and come back later without punishing him or her like that. Think of the shotgun trap in Resident Evil; if you pick up the shotgun and not put the broken one in its place, you trigger the crusher, and you get locked in that part of the mansion. However, you're not doomed, since you can just go back and put the shotgun back in its place to disable the trap and unlock the door to the crusher room so you can continue and come back later with the broken shotgun.

**Comment by nashmuhandes** [comment]
Good point. I will be addressing this when I have less on my plate.

**Comment by Tormentor667** [comment]
Totally agree

**Comment by nashmuhandes** [comment]
To be fair, the note right before the tiles specifically warns the player to "not be a fool, or it'll kill them", but I can see with modern player attention spans these days, they'll miss it, then blame the developers. :P

I think placing scripted autosaves around the map would be a good first step.

(god I hate modern gaming...)

**Comment by Blue-Shadow** [comment]
From what I understand from the note is that there's a specific path you need to take, starting from where the arrow is on the floor, obviously. But it doesn't matter where you start from, you'll still be killed, unless you discover the solution, of course.

**Comment by Tormentor667** [comment]
Well, I quite like to have that "try and error" principle in there indeed. Otherwise it feels very scripted and saving the player.

What about a different idea: The player can enter the church, walk into the floor but as long he hasn't the solution, he gets damaged and blasted back, so there is at lease some kind of dynamic and the player has te feeling, he can at leas try (even though he can't make it)?

**Comment by nashmuhandes** [comment]
Yeah, damage, instead of insta-kill, sounds way better.

I will remove the "must learn the solution" restriction, and make the tiles damaging.

**Comment by nashmuhandes** [comment]
Fixed and done (PS - it didn't work correctly before because the teleport destination thing was given the wrong tag, and also the parameters for the `Teleport` call in ACS were incorrect)
