### ISSUE TITLE
[TCOTD2] office chair looks too modern

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#108]
![image](https://user-images.githubusercontent.com/4926156/212488767-c920250e-8c04-46a8-a258-7680232e490e.png)

I'd suggest something more period-accurate. How about those voxelized antique-looking chairs from Blood?

**Comment by Blue-Shadow** [comment]
I agree. What do those chairs from Blood look like? (I don't own the game. I only played the shareware a long time ago).

**Comment by Tormentor667** [comment]
I agree and I am fine with the voxel ones.
