### ISSUE TITLE
[TCOTD2] Beds to pass time in shelter when close approaching nightmare

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#110]
So I found that, especially with the pendant (but even without the pendant, as like in the original 2007 version of the mod), I would just sit in the moon shelters when I know nightmare is approaching. This wastes precious real-life time.

I propose bedrolls inside shelters that the player can press +use on, that'll allow them to sleep, but ONLY if the nightmare timer is like around 95%. Attempting to activate the bedroll too early will just print a message that you don't feel tired yet.

(Additionally, door must be closed first - we don't want this to be an easy "panic button")

(multiplayer support - all players must be in a shelter + door must be closed, before allowing the sleeping procedure. Yes, doesn't matter if the players are in separate shelters - as long as each player is safely locked inside)

**Comment by Tormentor667** [comment]
If the player forgets to close the shelters, he does in sleep :)

**Comment by nashmuhandes** [comment]
Good idea. Perhaps I can make this into a mod, post-release. Imagine that, a mod of a mod. :P
