### ISSUE TITLE
[TCOTD2] Require player to light up the room under the mansion before being able to pick up the translation book

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#111]
Currently, if you are already aware of the translation book (by reading the letter in the brain storage), you can go to the dark room in the mansion and see a floating exclamation mark and the book in bright blue, despite the room being dark.

Should make it so that you have to light up the room first, which makes perfect sense - you can't look for something if you're in the dark!

**Comment by Tormentor667** [comment]
Agreed

**Comment by Blue-Shadow** [comment]
I'd say keep it as an option, since there's the lantern as an alternative to turning the lights on.

**Comment by nashmuhandes** [comment]
Ok, 2 checks for the dark room then -

- if player has no lantern, you will never be able to find the book
- if the player has the lantern and it is turned on, you will be able to find the book

**Comment by Tormentor667** [comment]
Perfect solution in my eyes

**Comment by nashmuhandes** [comment]
> Ok, 2 checks for the dark room then -
> 
> * if player has no lantern, you will never be able to find the book
> * if the player has the lantern and it is turned on, you will be able to find the book

Done
