### ISSUE TITLE
[TCOTD2] Turn sky to red when Thamuz is summoned

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#112]

**Comment by Tormentor667** [comment]
Green is the new red

**Comment by nashmuhandes** [comment]
Gonna need a new texture for it then. :D

**Comment by Tormentor667** [comment]
I should be able to take care of that :)

**Comment by Ozymandias81** [comment]
We could reuse the green vortex sky from final battle in BoA

**Comment by Tormentor667** [comment]
@Ozymandias81 - That would be awesome, can you port that?

**Comment by Tormentor667** [comment]
Has been ported by @Ozymandias81 thank you :)
