### ISSUE TITLE
[TCOTD2] Propose making player get the shotgun first before spawning the dog bosses

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#114]
Players are able to wander into the barn way too early in the game, with only a measly revolver and very few rounds, making it unfair. I suggest forcing the player to get the shotgun first, before spawning the dogs in the barn.

A message (and journal entries, when I implement that) can hint the player to investigate loud monstrous noises at the city center (where the barn is).

**Comment by nashmuhandes** [comment]
Oh, and to prevent the player from jumping up to go to the spider house too early, either lower the first haystack sector first so that the player can't jump, or... I don't know, seal the barn with a door or something (that only opens after picking up the shotgun)

**Comment by nashmuhandes** [comment]
Just realized it was precisely what Torm proposed, LOL, I think I'm getting a little burned out https://github.com/Realm667/Re-Releases/issues/29#issuecomment-1382191075

**Comment by Tormentor667** [comment]
> Just realized it was precisely what Torm proposed, LOL, I think I'm getting a little burned out [#29 (comment)](https://github.com/Realm667/Re-Releases/issues/29#issuecomment-1382191075)

Then let’s go for my idea :)

**Comment by nashmuhandes** [comment]
Done
