### ISSUE TITLE
[TCOTD2] "Barriers" in the church are passable

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#115]
They're those that appear in front of the doors (both of them) upon the boss's appearance - yeah, you can walk through them.

![Screenshot_Doom_20230116_132435](https://user-images.githubusercontent.com/4287687/212656640-8550380b-c7ba-4671-adaa-e2eaf7fa5a09.png)

**Comment by Blue-Shadow** [comment]
No, it hasn't. I just tested it.

**Comment by nashmuhandes** [comment]
I tried to take a look at this but I couldn't figure it how to fix it. :/ Gonna pass this one, sorry.

**Comment by Blue-Shadow** [comment]
If this can't be solved, then the best thing, probably, is to set up a "force field" in front of the doors. It can use the same texture as the one used for the barrier that appears during the hellhound boss fight. Hm?

**Comment by nashmuhandes** [comment]
> If this can't be solved, then the best thing, probably, is to set up a "force field" in front of the doors. It can use the same texture as the one used for the barrier that appears during the hellhound boss fight. Hm?

Fixed it exactly this way
