### ISSUE TITLE
[TCotD2] Journal and objectives system

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#116]
This is one of the big ones that I want to add, before I  consider my obligations to this project as "done".

I'd like to add an in-game journal that will keep track of player objectives and may some other misc info.

I already have working code for this from another project, I just gotta port it over and reskin the interface to look like a journal/book.

This will require some edits to the map to remove the linedef + ACS-based "letter reading" script.

**I have not started on this yet so it is safe to continue editing the map. When I want to start on this, I will announce it to make sure our works to the WAD do not collide**

**Comment by nashmuhandes** [comment]
Implemented. Press F1 in-game, or use the journal from the inventory bar.

Let me know your thoughts.

Some issues I'm already aware of:

- Would be nice to be able to close the menu by pressing F1 again
- Objective status isn't properly synched across all players in multiplayer
- Performance dips if the journal is open too long (infamous GC problem with ZForms - upgrading to a later version of ZForms will fix this. Very inconvenient and annoying work to do the code migration)

**Comment by Tormentor667** [comment]
Brilliant implementation so far. 

- One suggestion from my side: Make the text tan, not blue, fits better (keep the background darkblue though)
![grafik](https://user-images.githubusercontent.com/10298439/218319468-c599ccb0-d85a-4c47-a1b6-683bc5616009.png)
![grafik](https://user-images.githubusercontent.com/10298439/218319520-85223b76-a632-40ea-8774-d6b977fb7f34.png)

**Comment by Blue-Shadow** [comment]
> Make the text tan, not blue, ...

Is this color acceptable? It doesn't exactly match the color in your screenshot, but it's the closest to it from the stock colors available in GZDoom.

![jy6894](https://user-images.githubusercontent.com/4287687/221728276-2ac5e6df-0ecf-48ed-961e-a8b195fcc2c5.png)

**Comment by Tormentor667** [comment]
That’s perfect

**Comment by Blue-Shadow** [comment]
[Done](https://github.com/Realm667/Re-Releases/commit/d1a6f04055777ac70495ff72a160a95ef43c3ad8).

**Comment by Tormentor667** [comment]
Thank you!

**Comment by Tormentor667** [comment]
After taking a look at it once again after playing the mod, I really think we are done with it. Looks awesome and works perfect in my eyes. Feel free to reopen if you feel different @Blue-Shadow @Ozymandias81 @nashmuhandes but I think we are done here.

**Comment by Blue-Shadow** [comment]
> Font looks very aliased and dirty with no texture filtering in the journal page (NOT the note reader). Either increase font scale, or use a different font (something more handwriting-looking?). This problem doesn't exist when texture filtering is used (for obviosu reasons)

I'd like to see this resolved if possible, because I don't run the game on a high screen resolution (960x600 is what I use), and I don't use texture filtering because I generally dislike it (at least when playing Doom and the like). So this is how the journal looks for me (click on the screenshot to see it in full size).

![akdafkahdf33r43](https://user-images.githubusercontent.com/4287687/225485630-dca3f513-6b2e-4d5f-bf67-5a8bc39d21ee.png)

The text is pretty much illegible.

**Comment by Tormentor667** [comment]
Yes, good point. I have no idea what could be done about it though

**Comment by nashmuhandes** [comment]
Journal UI code needs a lot of fixes but I am currently undergoing heath issues (already personally messaged Torm beforehand) this is something that should be left to me to fix when I come back in a couple of weeks perhaps

**Comment by Tormentor667** [comment]
@nashmuhandes here as well - do you think that it's even possible to get this sorted before the release?

**Comment by nashmuhandes** [comment]
> @nashmuhandes here as well - do you think that it's even possible to get this sorted before the release?

The journal needs some rework to address all the problems mentioned in this thread, I hope to complete them ASAP

**Comment by nashmuhandes** [comment]
> > Font looks very aliased and dirty with no texture filtering in the journal page (NOT the note reader). Either increase font scale, or use a different font (something more handwriting-looking?). This problem doesn't exist when texture filtering is used (for obviosu reasons)
> 
> I'd like to see this resolved if possible, because I don't run the game on a high screen resolution (960x600 is what I use), and I don't use texture filtering because I generally dislike it (at least when playing Doom and the like). So this is how the journal looks for me (click on the screenshot to see it in full size).
> 
> ![akdafkahdf33r43](https://user-images.githubusercontent.com/4287687/225485630-dca3f513-6b2e-4d5f-bf67-5a8bc39d21ee.png)
> 
> The text is pretty much illegible.

I've made the journal and text larger on the screen - let me know if it's any better. :)

(still need to do scrollbars and finally keyboard/gamepad support... that will come later)

**Comment by Blue-Shadow** [comment]
> I've made the journal and text larger on the screen - let me know if it's any better. :)

Miles better! I can actually read the stuff now.

**Comment by Tormentor667** [comment]
Same here, it's a very good improvement.

**Comment by nashmuhandes** [comment]
Don't close this yet, there's still several issues left LOL

**Comment by nashmuhandes** [comment]
Added keyboard/gamepad navigation. Now all that's left is scrolling and scrollbars.

Good lord, UI coding is pure suffering LMAO

**Comment by nashmuhandes** [comment]
> Someone should create a framework for GUIs...

There already is one, it's called ZForms and TCOTD's journal is precisely using it. :P It's still not as simple as a WYSIWYG editor though :P But it's hell of a lot better than not having ZForms at all

**Comment by Tormentor667** [comment]
With "framework" I mean something like a WYSIWYG environment for people like me :)

**Comment by nashmuhandes** [comment]
I ultimately had to scrap the idea to implement scrollbars as I simply don't have the time and resources left to do it, but I did implement clickable buttons that simply scroll the pages up and down.

With this, the journal is technically feature complete and fully operation for all users of mouse, keyboard or gamepads, therefore I am closing this thread
