### ISSUE TITLE
[TCOTD2] Dagger key is required inside the mansion, too?

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#121]
I noticed there are some rooms in the mansion that are locked, and require the dagger key to open. To me, this seems superfluous; if you're in the mansion, then you have the dagger key already.

**Comment by nashmuhandes** [comment]
Yeah I noticed this too, I feel it's too restrictive. Plus it's annoying for debugging purposes when I warp inside the mansion, and then have to further give myself the key before I can explore inside. :P

**Comment by Blue-Shadow** [comment]
Yeah, the same here.

I went ahead and removed the locks. It could be a copy-and-paste error.
