### ISSUE TITLE
[TCotD2] What's new in the remaster?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#122]
I lost track a bit... here is a list that I'd like to expand with your help and add to the description and text file later on

- Improved gore effects (powered by Nash)
- Hires replacements for letters
- Hires replacements for textures (ai upscale with a grungy look)
- Revamped monster cast (improved enemies, new enemies)
- New final boss battle music
- New final boss (path of blood)
- New areas to discover (City Cistern, Gipsy Camp, Swamp)
- New puzzles, items and quests
- Expanded areas (new rooms in buildings, new shortcuts to avoid backtracking)
- New fullscreen HUD
- Added realistic special effects
- Added "Silent Hill"-esque snow effect 
- Added shader effects (movement and tilt)
- Turned doors into realistic polydoors
- Volumetric lighting
- Displacement maps
- Widescreen support (21:9)
- TITLEMAP instead of static graphic

**Comment by Blue-Shadow** [comment]
>     * Hires replacements for textures (ai upscale with a grungy look)
These were removed, weren't they?

**Comment by nashmuhandes** [comment]
- Combat tweaks with punchier weapons
- Actor optimization which allows thousands of objects to placed all across the map while still remaining fairly performant
- Massive cleanup of the scripting to bring it up to modern GZDoom development standards
- Journals and objectives
- Full coop support
