### ISSUE TITLE
[TCOTD2] Balancing the Death Incarnate

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#124]
Do we really need these guys to keep their ability to come back to life after being dispatched? They were originally designed with Doom in mind, where you tend to have plenty of ammo (and more weapons), not for survival-type gameplay where ammo is a little limited.

Playing though the game yesterday, I was doing well when it came to ammo, health and armor. All that, however, changed after they started showing up. I lost all of my super armor (which I picked up just before heading the other dimension), bullets, shells, and most of my medikits. It was kind of bad.

**Comment by Tormentor667** [comment]
I agree with that. I wonder: Can we add an mechanism that makes them respawn one time at max? So half of them instantly dies, half of them respawns one time but then definitely dies.

**Comment by Blue-Shadow** [comment]
Yeah, that can be done.

**Comment by Tormentor667** [comment]
Let's go for that then - can you change that behaviour @Blue-Shadow ?

**Comment by Blue-Shadow** [comment]
Done [here](https://github.com/Realm667/Re-Releases/commit/e88dc3742175f2aa082a90359506d9f4e1cf64d6).

**Comment by Tormentor667** [comment]
Thank you!
