### ISSUE TITLE
Revert to the old credits music?

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#125]
The current one doesn't have an ending, a conclusion. What I mean is, it was written to loop, unlike the old one.

"Okay, what's the problem?", I hear you say. The problem is that the ending sequence, after the music has fully played, plays the siren for one last time. With the old music it worked better; the music ends, a short delay of silence, and then you hear the siren. The current music just abruptly cuts at some point, which isn't as good.

**Comment by nashmuhandes** [comment]
I wasn't around when the music was changed; I was a little confused, too, about the choice of the new one.

**Comment by Tormentor667** [comment]
If all fails, we can revert the old one, I am fine with it.

**Comment by Blue-Shadow** [comment]
[Changed the music to the old one](https://github.com/Realm667/Re-Releases/commit/64abc02fdecb2c7514524d9f001bfad56437eb2d).
