### ISSUE TITLE
[TCOTD2] shotgun AltFire fails when you've fired one shell

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#127]
Looking at the code, I don't see anything wrong with it, but for some reason, the AltFire button just refuses to do anything if you have fired 1 shell.

You must fire a second shell, force the reload animation, _before_ being able to AltFire. This has cost me my life on many occasions.

**Comment by Blue-Shadow** [comment]
[Altfiring is disabled](https://github.com/Realm667/Re-Releases/blob/master/tcotd2/zscript/weapons/TCOTDWeaponSawedOff.zc#L34-L39) if you have the `SawedOffCheck` item, which is given after you fire one barrel.

**Comment by nashmuhandes** [comment]
Fixed
