### ISSUE TITLE
Most dynamic lights are too flickery - may trigger seizures

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#128]
A lot of the `FlickerLight`s in this mod have too big of a difference between their primary and secondary sizes. And because the map has a lot of dark scenes, these extremely-flickering lights may trigger seizures or discomfort for some people.

To fix this, generally lower the size differences of all `FlickerLight`s in the GLDEFS

**Comment by nashmuhandes** [comment]
Worst offender is the lights in the library's basement after turning the power back on, and also some of the lights outside of the church. There are others, too, of course - have to go through all of them and check one-by-one

**Comment by nashmuhandes** [comment]
Took care of the lantern and the library basement lights.

There may yet be more lights to edit, for sure... but I don't have time to go through them, currently

**Comment by Tormentor667** [comment]
After playing it for several timers now, I consider this to be solved.
