### ISSUE TITLE
[TCotD2] Hidden joke ending idea

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#129]
- Finish the game once, enter New Game+
- Shoot the explosive barrels on the boat
- Boat explodes and sinks
- Player complains that they can't go home now...
- Defeat Thamuz again after the above conditions are met to unlock a joke ending

(inspired by Silent Hill's dog/UFO ending)

**Comment by Tormentor667** [comment]
I like that :D
