### ISSUE TITLE
[TCotD2] New Game+ ?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#130]
Finishing the game will unlock New Game+ which lets you replay the game, keep all your weapons and ammo (but not keys and puzzle items obviously - also take away lantern and all lantern oil as there's more than enough oil pickups in the map for 1 playthrough). Lastly, monsters will

- Randomize?
- All move faster and have double health?
- Monster deals 1.5x damage?

**Comment by Tormentor667** [comment]
I like that approach. 

What about an additional time pressure element? E.g. you have a countdown running, and as soon as it is zero, nightmares will kill you. To gain additional time, you have various possibilities:

- Collect special items scattered around the map
- Do some additional quests (simple things, like passing items to certain places)
- Killing certain enemies that drop special items 

Just playing around with ideas.

**Comment by nashmuhandes** [comment]
Extra/new content will increase the scope of the work and further delay production. XD I have no objections, of course, but if new content were to be added, I most likely won't have time to oversee all of it. I can set up a basic New Game+ mode, and simply increasing enemy damage/health/speed is a simple task, but that's about all I can do with my limited availability.

**Comment by Tormentor667** [comment]
Good point as well. The danger with this decision is the loss of motivation and interest after the initial release of the remaster. I am not sure if people really are interested in a patch. The interest in Blade of Agony dropped massively after the 3.0 release towards 3.1 and 3.2

I think an easy addition next to the randomizer would be the timer, where you have to collect items around the map that add time to your remaining timer. There are so many small places and posts where you could hide them, it would greatly enhance the replay value without having to hazzle around too much.

**Comment by nashmuhandes** [comment]
Okay, if you want it to really hit on the initial release, then I suggest giving the project a little more time to cook. :)

How about setting October 31st as the _hardest_ deadline - BUT if it can be done earlier, the better?

**Comment by Tormentor667** [comment]
I am fine with that!

**Comment by nashmuhandes** [comment]
I will try to slowly and casually drum up the social media aspects of the project. I'll be talking about it on my Twitter as well as make some Youtube videos about it, in my spare time
