### ISSUE TITLE
[TCOTD2 Request] journal graphic

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#131]
![image](https://user-images.githubusercontent.com/4926156/215364388-428594db-a634-49c6-9a28-8fdfc2a05674.png)

I'd like to request graphics that look similar to this example, for TCOTD2's journal system. Sort of an old brown-ish book (not so clean, might have some small tears and crumples on the pages), and also tabs on the side for different categories of texts.

For the tabs, there should be an "active" and "inactive' state.

Best put into a PSD file with separate layers so I could further manipulate it.

**Comment by Tormentor667** [comment]
I can take care of that. What resolution do you need them?

**Comment by nashmuhandes** [comment]
> I can take care of that. What resolution do you need them?

Something befit of a 720p screen, perhaps. Not a fan of overly-high-res graphics in a pixelated Doom mod :P

**Comment by nashmuhandes** [comment]
Journal system is complete. The book graphic is currently borrowed from a Morrowind mod. Would prefer something less copyright-infringing

**Comment by Tormentor667** [comment]
I made something
![grafik](https://user-images.githubusercontent.com/10298439/218320046-8e407a1b-1551-4357-b47d-8935c7c9d3c2.png)

**Comment by nashmuhandes** [comment]
Yeah looks dope, will merge it tomorrow

**Comment by nashmuhandes** [comment]
@Tormentor667 looks dope, but the transparency is fucked

**Comment by nashmuhandes** [comment]
Ah, just saw that it was committed - looks great, thanks!

**Comment by Tormentor667** [comment]
Do you need any more graphics atm?
