### ISSUE TITLE
[TCotD2] Text-based credits crawler

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#133]
Would make updating it easier if it's not a graphic.

**Comment by Tormentor667** [comment]
Absolutely but no idea how to realize this the best way

**Comment by nashmuhandes** [comment]
I already have a credits scroller for my game DISDAIN. The credits are then written into a CREDITS.txt file. Once the whole system is in, it's just a matter of updating the text file, which anyone can easily do

**Comment by Tormentor667** [comment]
That’s cool. I still have the PSD so I can copy and paste the original text

**Comment by nashmuhandes** [comment]
I propose we split up the credits crawler into 2 sections, the Remaster section as well as a "Legacy Credits" section towards the bottom for the 2007 version.

**Comment by Tormentor667** [comment]
Yes, that makes definitely sense!

**Comment by Tormentor667** [comment]
Just for the record, here is the complete original credit roll as raw text

-------------------------------------

id Software 
   for Doom
			   
Monolith 
   for Blood
   Textures, sprites, music & sounds

Graf Zahl 
   for GZDoom	

Capcom 
   for Resident Evil
   Ingame music & sounds

Konami 
   for Silent Hill

BEthesda Softworks 
   for Daggerfall
   Some sprites for ingame decoration

Neoworm/Wildweasel
   Fence texture in outdoor areas

Cutmanmike
   for help with acs & pushable actors

Enjay
   Some Dark Project textures from his "Thief" 
   GZDoom effort

SnowKate
   Technical ACS Assistence

Mechadon
   for the ingame smallfont and bigfont

Shtbag555
   for web decorations

Scuba Steve
   for the dead scientist sprites & some useful
   tipps on how to enhance the gameplay

Eriance
   for Apprentice, Death Incarnate, Hell Hound,
   Nightmare, Vulgar, Wraith, Cultist

Neoworm
   for Ethereal Soul & the dual pistol code 
   and sprites

Vader
   for Soul Harvester, Shadow

DBThanatos & Jimmy91
   for Thamuz

KeksDose
   for all the new actor GLDEFS again as well as
   testing and development feedback

TheDarkArchon, HotWax & Graf Zahl
    for help and tricks with the custom weapons code.

Zippy	
   for special help and fixes with the custom 
   weapons code

Nash
   for Nash Gore effects

Chaoscentral
   for the script that forces OpenGL

ZBlood
   for several Blood resources I was too lazy for
   ripping myself

Hotwax 
   for help with sound for pushable objects

WildWeasel
   for a little sprite out of his WWHC-DIAZ weapon
   mod (pistol ammo) and help with the CustomPunch
   melee sound.

Neoworm & Eriance
   for the flying pitchfork sprites

Enjay & Gez
   for help with monster infighting & random
   script help

Risen & Graf Zahl
   for EVEN MORE random script help

Skippy
   for correct english grammar and improving
   the text files all over the place

Everyone else 
   I forgot and who helped me in the during public beta 
   test phase. Thx guys, you made this so much 
   better!
