### ISSUE TITLE
[TCotD2] Rework music player filtering

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#134]
Some songs should be heard globally, while some of them should only be heard locally (if a specific player triggers something). The entire system is currently inconsistent and buggy.

**Comment by Tormentor667** [comment]
Yeah it was never made with multiplayer in mind

**Comment by nashmuhandes** [comment]
Multiplayer is my specialty. :) I've spent several years learning the ins and outs of multiplayer, followed by actual production experience with my Strife Coop Patch mod, and also DISDAIN. Don't worry, I'll take care of it

**Comment by Tormentor667** [comment]
Awesome, thanks a lot :)

**Comment by Tormentor667** [comment]
I have taken a look at the current state of the script. To me it looks like you've already taken care of the music multiplayer compatibility. Is that correct?

**Comment by nashmuhandes** [comment]
Leave this issue open. It's not thoroughly investigated/tested. Will not be completed in time for this month's release - will have to be part of the future multiplayer update
