### ISSUE TITLE
[TCotD2] Add explanations to the difficulty settings

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#137]
I feel "normal" difficulty feels more like "easy" difficulty - I never run out of ammo and have waaaaay too much health. Normal difficulty needs to be tweaked so that it really feels more survival-horror-ey.

Hard and nightmare, then, would be made for really, REALLY skilled players.

**Comment by nashmuhandes** [comment]
Alternatively, bring back an actual "Easy" skill, that has the double ammo, halved enemy damage etc etc.

Then "Normal", "Hard" and "Nightmare" will gradually scale in difficulty, with the "Normal" baseline being very survival-horror-like (just enough ammo and health not too abundant), while "Hard" and "Nightmare" being for people who want crazy challenges. :P

**Comment by Tormentor667** [comment]
We added an explanation for each difficulty setting in Blade of Agony, I found that very helpful and intuitive and players would directly understand the differences.

That way, we might have a replay value as well, knowing the differences.

![grafik](https://user-images.githubusercontent.com/10298439/216113934-72f65109-e5ac-4722-a691-1fef569608f0.png)

**Comment by nashmuhandes** [comment]
I can add difficulty explanations, but I'll wait for the new BigFont assets to be completed first.

And to anyone who may be concerned - please do not bring in the BoA scripts for this. I will make clean, minimal and optimized solution specifically for TCOTD2.

I am generally trying to keep the overall code of TCOTD2 as lean as possible without any extra un-used baggage.

**Comment by Tormentor667** [comment]
Perfect, I am okay with it.

**Comment by nashmuhandes** [comment]
I've started some work on ammo balancing. It's definitely not final yet and needs more testing. Feel free to make changes if it's too brutal.

I'm trying to go for a survival horror feel

**Comment by Tormentor667** [comment]
> We added an explanation for each difficulty setting in Blade of Agony, I found that very helpful and intuitive and players would directly understand the differences.
> 
> That way, we might have a replay value as well, knowing the differences.
> 
> ![grafik](https://user-images.githubusercontent.com/10298439/216113934-72f65109-e5ac-4722-a691-1fef569608f0.png)

Any chance of getting this implemented somehow? I think it could be of good use, avoiding people who tell us that the mod is too hard because they expect the same style as with HMP and UV as comparison.

**Comment by nashmuhandes** [comment]
Changing issue title to reflect the actual pending work needed

**Comment by nashmuhandes** [comment]
I have decided to just use stock functionality with `MustConfirm` to explain the difficulty settings... we are running out of time and to be quite honest I am getting very burned out from working on this project by now (sorry) https://github.com/Realm667/Re-Releases/commit/fae6bc6e02766315bc1a12261e0dee9cd9de38fe
