### ISSUE TITLE
[TCOTD] Stats screen might need an upgrade

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#14]
With [this](https://forum.zdoom.org/viewtopic.php?f=18&t=69375) feature in, the stats screen, where you see your kills, items, secrets, etc, may need to be upgraded (keyword here is: _may_, since the feature isn't set in stone yet, it appears), because currently, this is how the stats screen looks like:

![Screenshot_Doom_20200724_103615](https://user-images.githubusercontent.com/4287687/88371508-d6c44280-cd9c-11ea-882a-e7262d8cdd70.png)

**Comment by Ozymandias81** [comment]
I know what to do here, I'll fix this at later stage. Thanks for let me know.

**Comment by Tormentor667** [comment]
What is this feature about?

**Comment by AFADoomer** [comment]
When set to 1, the 'sv_alwaystally' cvar forces a standard end-of-map tally screen to draw after maps, even if the nointermission flag is set in MAPINFO.  Currently, setting it to 2 also forces the draw of tally screens in between hub maps (this is in discussion in the ZDoom forum suggestion thread).

PWAD-style mods end up with the IWAD's tally screen shown, as in the picture above.  

IWADs (e.g., BoA) get the Doom-style tally screen with a black background, unless they include an INTERPIC graphic (this is why I added a texture definition for INTERPIC to BoA, so the screen will be less ugly if someone uses it).

**Comment by Blue-Shadow** [comment]
It gives the end user control to always have the game show the stats screen/intermission after a map is finished, even if the map explicitly prevents it from showing via MAPINFO.

**Comment by Tormentor667** [comment]
So if I understand this correctly, the player can force an intermission screen after the episode end even though the mapper did remove it for a reason?

**Comment by Blue-Shadow** [comment]
Yes.

In the case of TCOTD, it would go from the end text, to the intermission (what you see in the screenshot above), and then to the cast of characters, if the player had set the CVAR to 1.

The latest development builds of GZDoom has that feature, so you can test it if you want.

**Comment by Tormentor667** [comment]
I kinda find this decision questionable. I mean, why was this implemented? And what about forcing the cvar to be disabled for a modder?

**Comment by Blue-Shadow** [comment]
> 
> 
> why was this implemented?

You'll find the answer to that in the forum topic that I linked to.


> 
> 
>And what about forcing the cvar to be disabled for a modder?

It's either the player that gets control or the modder. It can't be both. In this case, it's the player. Think of it as the jumping feature; you can disable it in your map through MAPINFO, but the player can still force it through an option if they wish.

**Comment by Tormentor667** [comment]
Gave my 2 cents

**Comment by Ozymandias81** [comment]
Yeah this cvar is pretty odd, I think it won't be get very famous through modders XD

**Comment by Tormentor667** [comment]
Looks I am one of the few

**Comment by Tormentor667** [comment]
Well, looks like we have no chance of gettting this reverted again. Anyway:
https://github.com/Realm667/Re-Releases/commit/42acf8206cbc5ff5d2af25b123197ce63b020256
