### ISSUE TITLE
[TCotD2] Monsters which aren't meant to cast shadow do

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#141]
There are monsters, like the Nightmare and Wraith, which are flagged not to cast shadow. They still do, however.

Changing the sprite shadow option between _Default_ and _Monsters and players_ didn't make any difference.

I'm using 4.11pre-76-g4c0b5cbb3 of GZDoom, if that matters.

**Comment by Blue-Shadow** [comment]
After taking a look at the GZDoom source, the solution is to clear the CASTSPRITESHADOW flag from those monsters, while retaining the NOSPRITESHADOW flag.

**Comment by nashmuhandes** [comment]
> After taking a look at the GZDoom source, the solution is to clear the CASTSPRITESHADOW flag from those monsters, while retaining the NOSPRITESHADOW flag.

Should I fix this in GZDoom? Make it so that NOSPRITESHADOW has the last say?

**Comment by Blue-Shadow** [comment]
It's up to you.

**Comment by Blue-Shadow** [comment]
Resolved in 96c8642dcd642b0c3b08bfec0861619e72d72735 .
