### ISSUE TITLE
[TCOTD2] `LearnChurchSolution` script issues

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#142]
1. The discovery sound doesn't play (sound is misnamed).
2. There are, in total, two two-second delays (one from this script, and the other from the script that resurrects the zombies) before the zombies come back to life, which is more than enough to get out of there before they get back up to eat your face.
3. Until a music change is triggered later, there will be no music after the discovery of the solution.

**Comment by nashmuhandes** [comment]
Yeah, the sound mismatch is because after I committed the sound name changes and recompiled the map ACS, Torm committed the map with an older version because we were both working on the file at the same time. Will be fixed

**Comment by Tormentor667** [comment]
Meh, sorry for that :(

**Comment by nashmuhandes** [comment]
Fixed
