### ISSUE TITLE
[TCotD2] Hade spheres in the other dimension become active before going there

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#143]
The two hade spheres, you see highlighted in the screenshot below, become active before you go to the other dimension. This happens because, unlike the other enemies in there, they can potentially see you. The issue, here, is that due to portals and blah blah blah, you can hear their sounds in the "normal" dimension as they chase after you, but you can't see them.

Note: I"m starting to dislike portals, just saying.

![sghsfgdgs](https://user-images.githubusercontent.com/4287687/216797706-ce1e18c6-7065-4747-b9bf-cf838f261b83.jpg)

**Comment by nashmuhandes** [comment]
Yeah, I noticed this as far back as 2020 when this remaster project was just started. I didn't know what was going on at the time.

I wish there was a way to fix the portals so that they'd be "correct". I assume it's not as simple as just moving them in the right place?

**Comment by Blue-Shadow** [comment]
How about moving the monsters? When they see you, I believe that happens through the tent as you move around it on your way through gate towards the gypsy camp.

**Comment by Tormentor667** [comment]
That would be the better choice actually, less of a hassle.

**Comment by Blue-Shadow** [comment]
Resolved in 5a19aa3f5577210ea367c369eeefe605696e689b .
