### ISSUE TITLE
[TCOTD2] No siren nightmares in the cistern, intentional?

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#145]
If the siren nightmares spawn while you're in the cistern, you're safe from them, since they don't seem to spawn down there.

**Comment by nashmuhandes** [comment]
Yeah that sounds wrong. I'll place a few spawns in there

**Comment by nashmuhandes** [comment]
Added

**Comment by Tormentor667** [comment]
Thank you
