### ISSUE TITLE
[TCOTD2] Air shaft covers make no sound of their own when broken

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#146]
You can test this easily if you punch one of them with your fists. No sound when they break.

**Comment by nashmuhandes** [comment]
Same reason as before - SNDINFO logical sound names were changed, I compiled the ACS map script to to use the new names, but unfortunately Torm also was working on the map and had to overwrite my changes.

I am in the process of redoing all the progress I lost

**Comment by nashmuhandes** [comment]
Fixed
