### ISSUE TITLE
[TCOTD2] Air shaft covers that can be broken would benefit from debris and smoke

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#147]
...similar to the ones in Blade of Agony, as it simply looks a bit more realistic instead of just changing the texture.

**Comment by nashmuhandes** [comment]
I'll take care of that. Actually another thing I planned were destructible props - we got all these Build engine assets (barrels, etc) but they can't be destroyed. A lot of players whom I tested this mod with, expected the barrels to be destructible

**Comment by nashmuhandes** [comment]
Vents now spawn debris when broken, also made the zombie barrel and blood pole destructible. I plan to make a few more props destructible too (but need to also check that they don't break the level)

**Comment by Tormentor667** [comment]
Nice!
