### ISSUE TITLE
[TCOTD2] first or third person messages?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#148]
For stuff like picking up items, using items, scripted messages, etc. I noticed there's a lot of inconsistency here.

Should they be first or third person? I'm personally OK with which ever; all I'm concerned about is making them all consistent.

**Comment by Tormentor667** [comment]
I have to admit I never took care of it - so I am ok with both :)

**Comment by Blue-Shadow** [comment]
I'm leaning toward third person.

**Comment by nashmuhandes** [comment]
Agreed
