### ISSUE TITLE
[TCOTD2] Massive performance drop when snow is spawned over the ocean

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#153]
The FloorWaggle thinkers do _NOT_ play nice when a lot of actors are on top of a waggling sector.

Not sure if anything can be done about this, TBH. I may have some optimization ideas later

**Comment by Tormentor667** [comment]
Why not making them disappear when they hit the water anyway?

**Comment by nashmuhandes** [comment]
> Why not making them disappear when they hit the water anyway?

No, the performance issues kick in as soon as an actor exists in a waggled sector. They don't even have to hit the floor. It's because an actor simply existing in a sector already adds it to the thinker list

**Comment by Tormentor667** [comment]
Can they be excluded somehow from this handling? On the other hand, I wonder if the floor waggle is so important to have anyway here considering the ugly look at the shore border.

**Comment by nashmuhandes** [comment]
I have no objections if the waggle should be removed.
