### ISSUE TITLE
[TCOTD2] Disable player's name overlay during credits

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#154]
Otherwise, you get something like this...

![Screenshot_Doom_20230208_064139](https://user-images.githubusercontent.com/4287687/217426412-ce4c0096-246c-4dcf-9bb2-b8ce032bf9df.png)

**Comment by nashmuhandes** [comment]
Ah, woops. We have obviously not had the chance to test coop until the end yet... XP

**Comment by nashmuhandes** [comment]
Fixed
