### ISSUE TITLE
Make cistern elevator crush you from the bottom

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#155]
I tried messing around with Sector_SetLink but I have no idea how to do a crushing 3D floor. Someone else will have to take care of this one...

**Comment by Tormentor667** [comment]
Have you seen this? https://forum.zdoom.org/viewtopic.php?t=77265

**Comment by nashmuhandes** [comment]
> Have you seen this? https://forum.zdoom.org/viewtopic.php?t=77265

I have, and have tried it, but as mentioned in the thread - the crusher doesn't stop when on top of the player's head, making it very easy for the player to just move away with very minimal damage.

**Comment by Tormentor667** [comment]
Is this game breaking or can we just live with it as an “engine limitation”?

**Comment by Tormentor667** [comment]
Posted a thread at ZDoom.org https://forum.zdoom.org/viewtopic.php?t=77376 but to be honest, I really don't think that the whole effort is worth the gain so I am going to close this for now. If a solution is posted, I will consider adding it but it's low priority.
