### ISSUE TITLE
Offensive terms

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#157]
I have been told "gypsy" is an offensive slur and should be changed to make this mod friendlier in current year.

**Comment by Tormentor667** [comment]
Ugh…

**Comment by Tormentor667** [comment]
Took my time to find out more about the term, the usage and the meaning - and according to this explanation, I am more than insisting, to keep the term "gypsy" (with a lower-g)

https://www.grammarphobia.com/blog/2019/03/gypsy.html

**Comment by Blue-Shadow** [comment]
> Took my time to find out more about the term, the usage and the meaning - and according to this explanation, I am more than insisting, to keep the term "gypsy" (with a lower-g)
> 
> https://www.grammarphobia.com/blog/2019/03/gypsy.html

Another option is to simply remove it, and avoid a potential controversy!

I searched the game's files for the following words:

- gipsy
- gipsies
- gypsy
- gypsies

What I found:

1. Map's ACS scripts:
   - Line #2368: `gipsy`
   - Line #2400: `#define GOTO_GIPSY				77011`
   - Line #2456: `Script "GotoGipsy" (void) { Thing_Move(0, GOTO_GIPSY, FALSE); }`
2. Language.txt
   - Line #335: `	"- Gaul's Sands of Time, held within an ancient hourglass retained by the Gypsies of the Pandemonium Shadow Show, servants of the arch-demon for generations;"`
3. Letter graphics' metadata (not that someone is going to look there, but...).

Really, that doesn't seem to be a lot.

**Comment by Tormentor667** [comment]
I was talking to Nash the other night and after some discussion I am fine with changing the term.

**Comment by nashmuhandes** [comment]
Yeah let's change it completely. English isn't my first language so I'm currently not sure what's a suitable replacement.

**Comment by nashmuhandes** [comment]
> > Took my time to find out more about the term, the usage and the meaning - and according to this explanation, I am more than insisting, to keep the term "gypsy" (with a lower-g)
> > https://www.grammarphobia.com/blog/2019/03/gypsy.html
> 
> Another option is to simply remove it, and avoid a potential controversy!
> 
> I searched the game's files for the following words:
> 
> * gipsy
> * gipsies
> * gypsy
> * gypsies
> 
> What I found:
> 
> 1. Map's ACS scripts:
>    
>    * Line #2368: `gipsy`
>    * Line #2400: `#define GOTO_GIPSY				77011`
>    * Line #2456: `Script "GotoGipsy" (void) { Thing_Move(0, GOTO_GIPSY, FALSE); }`
> 2. Language.txt
>    
>    * Line #335: `	"- Gaul's Sands of Time, held within an ancient hourglass retained by the Gypsies of the Pandemonium Shadow Show, servants of the arch-demon for generations;"`
> 3. Letter graphics' metadata (not that someone is going to look there, but...).
> 
> Really, that doesn't seem to be a lot.

Took care of the variable names in the scripts

**Comment by Tormentor667** [comment]
Isn’t this already fixed by @Blue-Shadow ?

**Comment by Blue-Shadow** [comment]
No. The book of Thamuz graphic as well as its text-based representation in `language.txt`, I believe, are the only thing left.

**Comment by Tormentor667** [comment]
I can take care of the graphic if you update the language.txt :)

**Comment by Blue-Shadow** [comment]
I can't update the language file unless you update the graphic, first. :P

**Comment by Tormentor667** [comment]
We are funny 😃 well then: What term has Nash now used instead of Gypsy?

**Comment by Blue-Shadow** [comment]
> What term has Nash now used instead of Gypsy?

In the map's scripts, he used "caravan" as the replacement, but, obviously, it won't help in the case of the book, as it refers to the people who run the circus as the "Gypsies of the Pandemonium Shadow Show".

**Comment by Tormentor667** [comment]
What I could imagine is calling them "waybearers", at least the term works in german.

**Comment by nashmuhandes** [comment]
Whatever works - english isn't my first language, and all I'm concerned about is the original word scrubbed off the project. :)

**Comment by Tormentor667** [comment]
Then let's go for the waybearers / Waybearers of the Pandemonium Shadow Show" if @Blue-Shadow thinks that the term works as well.

**Comment by Blue-Shadow** [comment]
As I don't have a suitable term, yeah, let's go with it.
