### ISSUE TITLE
Vents are a cheap way to camp from the nightmares

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#158]
You can hide safely in the vents during the siren. A possible solution is to add creepy vent crawler enemies that materialize during sirens

**Comment by Tormentor667** [comment]
Or make the nightmares completely invisible and reduce their height so they can enter the vents. Optionally we could simply "kill" players in vents through scripts the same way as they get killed by the nightmares.

**Comment by Tormentor667** [comment]
I've seen that the Nightmare's height is 30 units, pretty sure that this way they are able to enter each vent, so this can be safely closed.
`/////////////////////
// SIREN NIGHTMARE //
/////////////////////
class SirenNightmare : KDiZDNightmare
{
	Default
	{
		//$Title Siren
		Health 300;
		Radius 10;
		Height 30;
		Speed 10;
		Scale 1.5;
		SeeSound "nightmare2/sight";
		PainSound "nightmare2/pain";
		DeathSound "nightmare2/death";
		ActiveSound "nightmare2/active";
		-COUNTKILL
	}

	States
	{
	Melee:
		NMRE E 0 A_SetShootable();
		NMRE EF 9 A_FaceTarget();
		NMRE G 9 A_CustomMeleeAttack(100 * random[rnd_SirenNightmareDmg](1, 8), "nightmare2/melee", "", "Fear2", false);
		Goto See;
	}
}`
