### ISSUE TITLE
[TCOTD] Not included in _build-all

### ISSUE THREAD

**Issue by DevilBlackDeath** [Realm667/Re-Releases#16]
Hey,
Nothing huge, I just wanted to point out TCOTD1 is not included in the _build-all.bat. It still builds correctly, it's just the build batch file for TCOTD is not called by _build-all.

Have a good day !

**Comment by Tormentor667** [comment]
Thanks for the hint, I will just fix it.

**Comment by DevilBlackDeath** [comment]
You're welcome ! I don't know if that's planned as a non-github release (I assume so) in which case the wads will likely be pre-built, but hey I know that's the kind of small thing that can be annoying when working on projects internally ;)

**Comment by Tormentor667** [comment]
It will be, but still there is a lot of work left to be done so don't expect that too early ;)
