### ISSUE TITLE
[TCotD2] New enemy proposal

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#160]
I think that one might fit well at various places, what do you think?
https://www.realm667.com/en/beastiary-mainmenu-136-69621/other-style/2489-venor

**Comment by nashmuhandes** [comment]
Yup looks great, go for it

**Comment by Tormentor667** [comment]
Shall I add it or do you want to do your zscript magic?

**Comment by Tormentor667** [comment]
Added for now.
