### ISSUE TITLE
[TCotD2] Offset of journal icon needs to be moved farther to the top

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#161]
![grafik](https://user-images.githubusercontent.com/10298439/218320359-f3821ec4-9a32-4a02-98fc-9ffde8d7da1b.png)

**Comment by nashmuhandes** [comment]
This problem actually affects all items in the box, not just the journal. And it has been bothering me, yes.

**Comment by Blue-Shadow** [comment]
[Fixed](https://github.com/Realm667/Re-Releases/commit/2f8fc72eb03704921e9f3d7f9b66aeeae25ca0b5).

**Comment by Tormentor667** [comment]
Thank you!
