### ISSUE TITLE
[TCOTD2] Noticeable performance drop when looking towards the sea

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#166]
When I say "noticeable", I mean the frame rate drops below 30/35 fps :P

I imagine it's got something to do with the water being a 3D floor now, because I didn't get this performance drop before.

**Comment by nashmuhandes** [comment]
Yeah, I complained about this with Torm in DMs, too.

Actually my first suspicion are the massive amounts of triangulated slope sectors. This is actually an overall problem all over the outdoor areas - there's too much geometry being used for things that can't even be seen.

Anyway, I'll have to get back here when I figure out why is the beach so FPS-draining now.

**Comment by nashmuhandes** [comment]
Found the cause - the reflective floor from when before the ocean was 3D, was being applied to the ground beneath the ocean. Simply removing the reflections, fixes the performance

**Comment by Blue-Shadow** [comment]
It's a lot nicer now, thanks!
