### ISSUE TITLE
Those triangulated sectors are a huge source of performance drops

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#168]
In my view, they are mostly completely unnecessary - you don't see much difference in the geometry (compounded by how dark the mod's overall aesthetic is) but yet they cost so much performance.

Not only that, those triangulated floors actually cause movement glitches - player will sometimes slide around without stopping, or will cause the player to sometimes get a speed boost. ZDoom's movement code is just glitchy like that with slopes.

I have a quick edit I did that removes all that unecessary geometry and the framerate cadence improves SO much from this. I have deliberately not committed this file though, because

A) I might've messed something up - I only very quickly did this to prove a point
B) I'd like to create a discussion about this before we actually commit to it - if you insist on creating triangulated/sloped terrain, you need to reduce the amount by a LOT. And lastly, if you absolutely want to create sloped terrain, it MUST be VERY noticable (the ground's silhouette must look different enough to justify the extra resources needed to render them)

Attaching my edited map for appraisal.

[MAP01.zip](https://github.com/Realm667/Re-Releases/files/10777147/MAP01.zip)

**Comment by Tormentor667** [comment]
I am actually surprised that this has such a big performance hit to be honest. 

Why did I make them triangular? I simply wanted to make the outdoor aesthetics feel more natural and less blocky. If we can achieve this with less sectors, I am okay with it.

**Comment by nashmuhandes** [comment]
Yeah but here's the thing. The extra geometry aren't visible. So many sectors on the map but to my eyes, everything is still a flat ground.

Also, I am using an IPS monitor with calibration (I do graphics and video-work too) so I definitely don't have crappy monitors. ;)

Testers have also said they don't notice any difference in the ground geometry, unless they look really, REALLY hard.

Lastly, as I said, the bigger problem is that those small sloped sectors cause movement glitches. Players seem to slide uncontrollably over them and can sometimes get a weird speed boost, depending on the angle they're facing.

**Comment by Blue-Shadow** [comment]
I agree. For nearly-flat surfaces, the slopes have to go. You simply can't see the effect, yet it causes the aforementioned and annoying slippery movement.

**Comment by Tormentor667** [comment]
Fixed

**Comment by nashmuhandes** [comment]
Thanks, will do a full playtest soon. I just got back from my hiatus.
