### ISSUE TITLE
Different color schemes in menu

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#170]
I noticed some inconsistency of the menue colors. Compare the original options menu:
![grafik](https://user-images.githubusercontent.com/10298439/221255246-31f8a79b-829e-4236-b6b0-17937e307744.png)
and the enhanced options:
![grafik](https://user-images.githubusercontent.com/10298439/221255298-4b774d2d-8b47-4f91-b27d-ada429289e8a.png)

I'd also suggest changing the color of the headlines in the submenues as well as all other occurances of red to something more fitting.

**Comment by Blue-Shadow** [comment]
Why don't you [play around with the colors](https://zdoom.org/wiki/MAPINFO/GameInfo_definition#MenuFontColor_Title) and see if you come up with something you like?

**Comment by Tormentor667** [comment]
Ah very good, thanks for pointing me towards this. I feared that we have to rewrite the menudef instead of being able to change the colors through this place. I will take care.
