### ISSUE TITLE
Mall sells skulls

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#171]
Hm...

![Screenshot_Doom_20230227_055507](https://user-images.githubusercontent.com/4287687/221462401-f691ae21-996b-462f-a16b-bbae134cf2b2.png)

(Make sure to check all the shelves, as the one you see in the screenshot isn't the only one)

**Comment by Tormentor667** [comment]
I actually did this on purpose - too grotesque? 😀

**Comment by Blue-Shadow** [comment]
I had the feeling it was on purpose.

> too grotesque? 😀

It's more like strange/makes no sense that the local mall sells human skulls...

**Comment by Tormentor667** [comment]
If it feels out of place, I can replace it with something else
