### ISSUE TITLE
Boxes in water block movement

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#172]
You can't move underneath the boxes that are floating in the water, as your movement is blocked.

![Screenshot_Doom_20230227_094655](https://user-images.githubusercontent.com/4287687/221494163-f3bb5011-c6ee-42da-af79-217256c7be3d.png)

**Comment by Blue-Shadow** [comment]
> It looks like everything is set up right in the editor

I've taken a look myself. The linedefs that make up the boxes all have the "Block Everything" and "Impassable" flags

![ghfhd668](https://user-images.githubusercontent.com/4287687/221775511-eb1b4c33-ef5f-404c-abc3-ef0ab4c26c0c.jpg)

**Comment by Tormentor667** [comment]
Fixed it.
