### ISSUE TITLE
Butcher's homing attack removal

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#173]
It's just vomit (or whatever), not a high-tech heat-seeking rocket or a magical ball of energy.

**Comment by Tormentor667** [comment]
I am okay with changing it, I didn't even notice that it is homing :)

**Comment by Blue-Shadow** [comment]
> I didn't even notice that it is homing :)

That's because, currently, there's a bug or oversight in the projectile's code which prevents it from functioning as a homing projectile. It did work in the original version of TCOTD2, though.

**Comment by Blue-Shadow** [comment]
[The attack has been removed](https://github.com/Realm667/Re-Releases/commit/f5e2deb4bd20840307de598bb88e4096c43e9eef).
