### ISSUE TITLE
Pistol and pitchfork don't autoaim

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#174]
Is there a legitimate reason why auto-aiming is disabled for these weapons? As a keyboard-only player, weapons that require manual aiming are a big problem for me.

**Comment by nashmuhandes** [comment]
Can't think of a reason why that is. Feel free to add it in.

(this thread also reminds me that the journal needs to be fully keyboard/gamepad navigate-able...)

**Comment by Tormentor667** [comment]
Seconded

**Comment by Blue-Shadow** [comment]
Addressed [here](https://github.com/Realm667/Re-Releases/commit/a7c4aef12487b01548cbe8252db335b2845617e4).
