### ISSUE TITLE
Something wrong with the lampposts outside the church

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#175]
![Screenshot_Doom_20230311_041218](https://user-images.githubusercontent.com/4287687/224456390-0adcd3be-5ec8-495d-b111-2f1cc42d9165.png)

**Comment by nashmuhandes** [comment]
Wild guess here is that this got messed up during the geometry-reducing pass

**Comment by Tormentor667** [comment]
Fixed
