### ISSUE TITLE
[TCotD2] Antidote letter

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#177]
- [x] Need to create the actually-readable letter class
- [x] The graphic asset's resolution doesn't match the rest of the letters (use the PSD assets to create the proper graphic)

**Comment by Tormentor667** [comment]
Added the hires letter

**Comment by Tormentor667** [comment]
@nashmuhandes how are you? Potentially back in business for getting this one done? :)

**Comment by nashmuhandes** [comment]
@nashmuhandes currently busy elsewhere but will return to this project as soon as I can (some time this month). I am committed to stick to my guns for this project

**Comment by Tormentor667** [comment]
Great to hear, can't wait to have you back in action and bringing this to a releasable state :)

**Comment by Tormentor667** [comment]
Thank you for fixing
