### ISSUE TITLE
About `_build-all.bat`

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#178]
Seems like it's done in an inefficient way where every command line from each individual sub-project is duplicated. So for example, if I update the `tcotd2_build.bat` file, I'd ALSO have to update the corresponding line inside `_build-all.bat` file.

This is very error-prone.

A better way is to have `_build-all.bat` actually call the other BAT files in sequence.

**Comment by Tormentor667** [comment]
Brilliant @Ozymandias81 :)
