### ISSUE TITLE
[TCotD2] Poisining effect

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#183]
Currently it's possible that the player can be poisened by chance by the vulgars. I'd suggest that the Red Cross indicates this somehow as well as soon as you are poisened as the screen effect is very subtle.

What about giving the red cross icon some kind of "slime poison" effect @nashmuhandes 

![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/6ed88083-5d65-481e-a29e-f593e17f744f)

**Comment by Blue-Shadow** [comment]
Done in d8e593aa5b67a7fbb372ad29ba1aa845f02b026e. Though whether you like the icon or not is a different matter.


![Screenshot_Doom_20231013_024744](https://github.com/Realm667/Re-Releases/assets/4287687/e8fc0a4f-b385-43aa-aecf-270d39e717f0)
