### ISSUE TITLE
[TCotD2] Removing the cutscene from the dog battle

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#184]
I have posted it in a different issue already but somehow that got lost. I'd suggest removing the camera cutscene from the dog battle again, it's simply more distracting and atmosphere-killingt then it's improving the gameplay. Could you make the encounter more natural and fluid again @nashmuhandes ?

**Comment by Blue-Shadow** [comment]
> I have posted it in a different issue already but somehow that got lost.

It's issue #132, which has more discussion, so I'm closing this one.
