### ISSUE TITLE
[TCotD2] Fire borders in boss battles

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#185]
I'd suggest adding a shader to the fire textures to make them more natural looking, maybe you have something for this @nashmuhandes . Also, after the battle the walls instantly disappear. Making them fade in and out in about 35 tics would look much better.

**Comment by Blue-Shadow** [comment]
> Also, after the battle the walls instantly disappear. Making them fade in and out in about 35 tics would look much better.

Done in 71d2be2568a5a51a318e1c468dccade0125d6f69.
