### ISSUE TITLE
[TCotD2] Sound for breaking spider webs

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#186]
These two places simply make the web disappear instantly without any effect.

![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/049f72f4-f73c-4b63-8d3a-0627a517c2cb)
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/6d10a7ca-9a9a-419a-ada3-ef351021996f)

I think both would benefit a lot from spider web pieces debris and smoke to make the effect of spiders breaking through more convenient.

**Comment by nashmuhandes** [comment]
Added debris in https://github.com/Realm667/Re-Releases/commit/cde20156bd674b39452cd758f1d96ee9ab05cda4 someone else will have to take care of the sound because I don't have time to go sound sample hunting

**Comment by Tormentor667** [comment]
[strong-hit-36455.zip](https://github.com/Realm667/Re-Releases/files/12919604/strong-hit-36455.zip)
I think this should do the job.

**Comment by nashmuhandes** [comment]
Used a sound from Blood and incorporated it in https://github.com/Realm667/Re-Releases/commit/41d5cb4825d5ca285cf0481300fcf5e9e1f9bdb2
