### ISSUE TITLE
[TCotD2] Objective isn't greyed out

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#187]
even thogh I learned how to enter the church safely and even made it @nashmuhandes 
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/e31b84a8-e579-47b5-8686-e35d621c1f4e)

**Comment by Blue-Shadow** [comment]
During my play-through yesterday, I avoided the hospital entirely until way later in the game. By the time I came to explore the hospital, I had the mortuary key with me, yet I still got the objective of looking for it which was never marked as completed.

**Comment by nashmuhandes** [comment]
Should have fixed both of these with https://github.com/Realm667/Re-Releases/commit/45d9c99d9faeb935f534e14d10b303cd40fdea71, please test and close the issue if confirmed

Future quest objective glitches please make a new issue

**Comment by Blue-Shadow** [comment]
Seems fine.
