### ISSUE TITLE
[TCotD2] End Sequence is broken but was planned afaik?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#190]
The ending sequence is broken in general, but afaik @nashmuhandes planned to fix it up anyway by turning it into real text and no graphic anymore. This is essential actually, as it isn't working as of now.

![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/1232edf6-6df5-49bc-94a4-2c219b5b3790)

**Comment by nashmuhandes** [comment]
Yes, still pretty much on the docket - closing this as duplicate

**Comment by nashmuhandes** [comment]
https://github.com/Realm667/Re-Releases/issues/162

**Comment by nashmuhandes** [comment]
Reopening this to keep track of the new ending sequence
