### ISSUE TITLE
[TNT1 & TNT2 & TNT3 & TNTLE] Can't be launched at all

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#192]
@Ozymandias81 do you have an idea why?
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/a4556594-ca83-4b33-92a6-b07e321d82f9)

**Comment by Blue-Shadow** [comment]
In the erroneous lines, there's a variable which is named `finished`. It should be changed to `finishedp`.

**Comment by Tormentor667** [comment]
Changing that leads to this
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/84934284-7422-4b80-9ea7-3ab91df2bed1)

**Comment by Blue-Shadow** [comment]
It's the same thing; change `finished` to `finishedp` in that line.

**Comment by Tormentor667** [comment]
Thank you, it works now :)
