### ISSUE TITLE
[TCotD2] Blindness effect for nightmares

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#195]
I found that effect pretty cool blinding you for a few seconds if their attacks hit you. Can you reimplement that again and weaken their attacks a bit making less damage? The blinding effect should be challenging enoigh @Blue-Shadow

**Comment by Blue-Shadow** [comment]
That effect isn't my doing. It's been there since before my gameplay tweaks. There's an open discussion about changing the color or possibly getting rid of the effect entirely, actually (see issue #140).
