### ISSUE TITLE
[TCotD2] Area needs texture color fix

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#196]
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/ad294a64-00d6-4678-9b8f-87cac4175b5d)
in the laboratory of Steiner

**Comment by Blue-Shadow** [comment]
Could you elaborate on what needs changing?

**Comment by Tormentor667** [comment]
This is just a reminder for me, it’s about the wood texture colors. I will normalize them.

**Comment by Blue-Shadow** [comment]
The stairs leading to the second floor in the mansion are exactly like those, by the way. Just in case you want to give them the same treatment.

**Comment by Tormentor667** [comment]
Fixed.
