### ISSUE TITLE
[TCotD2] Window lights don't get correctly relit after city lights turn on again

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#198]
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/09c9e9fa-a3dc-444f-8f16-bf89a353725e)

**Comment by Blue-Shadow** [comment]
Fixed the light effect on the floor in a13843d57d9bdfef22e49f6a1e2619efd3cd1737.

What I didn't fix, though, is the texture of the window itself; it needs to change to a lights-are-off version and then back after the nightmare ends.

**Comment by Tormentor667** [comment]
Fixed as well
