### ISSUE TITLE
[ZPack] Ammunition number offsets are "off"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#20]
The numbers at the right should be higher somehow
![grafik](https://user-images.githubusercontent.com/10298439/125345336-b6e4b080-e358-11eb-8a2e-16f394cd1a28.png)

**Comment by RichardDS90** [comment]
I'll see if I can make a new SBARINFO to fix that.

**Comment by Tormentor667** [comment]
Learning by doing :)
