### ISSUE TITLE
[TCotD2] Leaving the cistern doesn't get activated

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#200]
I left the cistern and still didn't get it completed:
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/5074fcdf-e229-44e6-830d-fbd9ec10d30c)
@nashmuhandes

**Comment by nashmuhandes** [comment]
Did you leave properly or with cheats? The trigger is some linedef just before the elevator. Maybe I'll add more triggers

**Comment by Blue-Shadow** [comment]
Fixed in 3a06f777ea6746d5267233b3460b51adaf03c4c2.
