### ISSUE TITLE
[TCOTD2] Slope issue outside the church

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#201]
This sector is supposed to slope all the way down, but it isn't and I don't know why. The issue manifested after my work earlier today in that area to fix the fence.
![Screenshot_Doom_20231002_104645](https://github.com/Realm667/Re-Releases/assets/4287687/a5046136-9e7a-4a2e-8550-be6c4d903894)

**Comment by Blue-Shadow** [comment]
After further observation, the issue manifesting seems random? Sometimes the slope is fine and other times it's not. Today I found another slope that suffers from this.

![Screenshot_Doom_20231004_085613](https://github.com/Realm667/Re-Releases/assets/4287687/dd494d65-2730-4e38-9fbe-e0d69344b5a8)

**Comment by Tormentor667** [comment]
What version of GZDoom are you using? I can not reproduce any of these.

**Comment by Blue-Shadow** [comment]
I'm using 4.11.0. Saying that, I don't seem to have encountered it the last couple of days or so during my various test runs of the map. Weird.
