### ISSUE TITLE
[TCotD2] Cutscene for the final Bossbattle

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#205]
According to this issue https://github.com/Realm667/Re-Releases/issues/132 there has been a discussion about the cutscene of the boss battle. To be honest, I am not a big fan of a scripted, camera-swapping cutscene at all as it conflicts a lot with the atmosphere, dynamic and the whole feeling of the mod, so I'd like to avoid something similar to the dog battle cutscene.

Instead though, I could imagine a good spawning animation/script for the final boss when he gets summoned. Currently, he is instalty there and attacking you which is kinda unfair anway. Some small scripted animation should do the job for about 5-6 seconds.

**Comment by nashmuhandes** [comment]
Nothing too ambitious, but addressed with https://github.com/Realm667/Re-Releases/commit/922e77db3b9e911bce6665ff1d9a56d6bedaba7e
