### ISSUE TITLE
[TCOTD2] Objective to find the spider key

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#208]
Since the spider key is such an integral part to the overall progress, it's worth adding an objective just for it. Interacting with anything that needs the spider key will add the objective, and picking up the key will complete the objective (duh)

**Comment by nashmuhandes** [comment]
![image](https://github.com/Realm667/Re-Releases/assets/4926156/e711f743-ac8d-45fe-9a53-c02f02ae6cd2)

Came up with a neat little sub-plot. The cult kidnaps women around the city to do dark experiments and rituals on them. One of the victims is a girl named Alianna, and she was kidnapped to be turned into the Spider Queen. You will find a note on this poor dude who was his lover, which will add an objective to find the girl (naturally, leading you to the spider boss).

I still intend to reskin the actual spider boss sprites to make it look unique

**Comment by Tormentor667** [comment]
Very nice addition :) Fits the atmosphere quite well!

**Comment by nashmuhandes** [comment]
Technically already addressed just by reading Richter's letter
