### ISSUE TITLE
[TCOTD2] Spider queen letters

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#218]
@Tormentor667 need your help to proof-read/improve/finish up the spider queen stories.

- Check and edit the LANGUAGE entries: https://github.com/Realm667/Re-Releases/blob/e1186cedd421b16e8cc29cb03ca1826a071dbb70/tcotd2/language.txt#L554 and https://github.com/Realm667/Re-Releases/blob/e1186cedd421b16e8cc29cb03ca1826a071dbb70/tcotd2/language.txt#L561

- Create the high res letter graphics (`LETTER21.png` and `LETTER22.png`)

**Comment by nashmuhandes** [comment]
Some additional context:

- Richter's body is found near the crates at map coords `[1280, 6556]`
- Alianna's letter is found in the barrel puzzle chamber at coords `[-18560, 3456]`. It is implied that she was kept and tortured here before being forced to transform to the spider queen through some unspeakable ritualistic horrors...

**Comment by Tormentor667** [comment]
Richter's text works fine. 
Alianna's text needs some work. I imagine something like this:
--------------------
_Richter, my love... I should have listened to you... the wicked cultists have locked me up here, without water and food. They put a vial in the cell every day for me to drink, but so far I refuse and throw it against the wall.... I just don't know how long I can do it anymore. One of the cultists, he seems to have a lot of knowledge about the nature of evil, keeps talking at me. His piercing gaze is almost hypnotic.... I'm hungry Richter, I'm so thirsty and I can't stand the torture any longer. You promised me that the pain would end as soon as I complied.... I am afraid, but I break.... my love, I should have listened to you.... Forever, Your Alianna_

**Comment by nashmuhandes** [comment]
To do: make Richter's letter less angry/gaslight-ey and more remorseful + desperate

**Comment by nashmuhandes** [comment]
Fixed the letters in https://github.com/Realm667/Re-Releases/commit/024279e1c8cfbdd27fe70fe773aaa715a789cb65
