### ISSUE TITLE
[TCOTD2] Restore the cultist sounds

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#220]
The cultist sounds have this weird low-pitch effect on them. I think they sound terrible. I suggest restoring the sounds to their original pristine samples as ripped from Blood.

**Comment by Tormentor667** [comment]
I am okay, it's not that I care :)

**Comment by nashmuhandes** [comment]
Done with https://github.com/Realm667/Re-Releases/commit/cfe6c121b2fc1516210c2d08a6aede95da4505c2
