### ISSUE TITLE
[TCOTD2] Some tiles in church hurt but don't teleport

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#221]
Walking on some of the "wrong" tiles in the church hurt the player but sometimes they don't cause the player to teleport. The reason for this is because some of the lindefs which have the action to teleport and damage are triggered from the back side. Teleporters can only be triggered if crossing a lindef from the font side.

**Comment by nashmuhandes** [comment]
Some of the lines are also apparently set as unrepeatable. What a mess! I'll try cleaning it up now.

**Comment by nashmuhandes** [comment]
Hopefully fixed with https://github.com/Realm667/Re-Releases/commit/f508982f73d79210f0705952adb4f7d1c131f23a

**Comment by nashmuhandes** [comment]
Oof, actually not fixed at all, reopening >_<

**Comment by nashmuhandes** [comment]
Fixed it in https://github.com/Realm667/Re-Releases/commit/7f6c8d4c5e09168d9130876b38e8265c0c5e3f4e for real. The solution was not to mark the lines as "activatable from the back", that didn't seem to even work (Teleport seems to be hardcoded to only be activate-able from the front? Dunno, didn't check engine source, don't care, I don't have time LOL) -- instead, I just use Teleport_Other on the player, which seems to work.

**Comment by Blue-Shadow** [comment]
> Teleport seems to be hardcoded to only be activate-able from the front?

It is, otherwise you wouldn't be able to, let's say, get off a teleporter pad from which you can teleport as well.
