### ISSUE TITLE
[TCOTD2] Checking out the freezer isn't worth it anymore

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#222]
The freezer contains three wraiths and one shotgun shells pickup. Previously you could pitchfork the monsters in there to death so you don't have to use some of your ammunition. Now that those monsters can't be harmed by the pitchfork (or fists), you have to use some of your ammunition to get rid of them. But the reward is just two shotgun shells.

![Screenshot_Doom_20231013_063016](https://github.com/Realm667/Re-Releases/assets/4287687/117c217b-2a0c-44c7-a6a1-30e418950b45)

**Comment by nashmuhandes** [comment]
I also thought this room became pointless now. Some ideas on what to do with this room:

- Add an antidote? (not sure if this would be one too many and upset the current balance)
- Just remove the wraiths then, or replace them with a low-difficulty encounter to make the ammo reward more worth it?

Additionally, I think the vents at the sides of the room where you can see into the fridge is hilarious and doesn't make sense (I thought fridges are meant to be sealed...)

**Comment by Blue-Shadow** [comment]
I'd go for the second one, since just upstairs in the pub, there already is an antidote.

**Comment by nashmuhandes** [comment]
Attempted to address it with https://github.com/Realm667/Re-Releases/commit/0687af98ed21de20dec507c0497ed6d7ed7968e3 ...
