### ISSUE TITLE
[TCOTD2] You can see into the locked rooms of the hospital from the outside

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#223]
You're able to see into the locked rooms, as well as the rather anti-climactic axe zombies, from outside the hospital windows, trivializing the entire thing. :P

**Comment by Blue-Shadow** [comment]
Who left the curtains open? Hint, hint...

**Comment by nashmuhandes** [comment]
Fixed with https://github.com/Realm667/Re-Releases/commit/a3acbb4b46cf0ac677794bb3e9928a73e2a0840f I really think the encounters shouldn't be spoiled from the outside
