### ISSUE TITLE
[TCOTD2] Activating the candelabras in the upstairs pub changes the model size

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#225]
Additionally, the "on" state of the candelabra doesn't even have any dynamic lights attached.

(Consider making them not toggle-able on use?)

**Comment by Blue-Shadow** [comment]
Fixed in dbd84c61f9f40c9515cb17ad98fc52576251cae4.

> (Consider making them not toggle-able on use?)

I left them toggle-able as they are, since I don't want to touch the map right now in case you're doing some work.

**Comment by nashmuhandes** [comment]
All fixed in https://github.com/Realm667/Re-Releases/commit/8e73dde0555c093c062f692c24ff78bd0e37ba3c
