### ISSUE TITLE
[TCOTD2] Relocate the super armor and Tommy gun

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#230]
These two powerful items can be obtained, pretty much, at the start of the game, as there's nothing that blocks the player's path to them. We don't want the player to feel that powerful right from the start, now do we?

**Comment by nashmuhandes** [comment]
Yeah, agreed. Had this thought earlier today. Boondorl also pointed out that you pretty much get every weapon except the napalm launcher early on, and then nothing else until almost at the very end.

Maybe save the Tommy for the inner sanctum? With the enemy count inside there, it might be tempting to just go blasting inside there.

**Comment by nashmuhandes** [comment]
As for the super armor, we could keep the "mouth" closed until after the player presses the button to open the gates to the other dimension. This makes sense, it's like a switch that "activates" the attractions in the circus...

**Comment by nashmuhandes** [comment]
Done with https://github.com/Realm667/Re-Releases/commit/871dda9752e745dab526e68ec9836ef63ffe1747 let me know if that's better

**Comment by Tormentor667** [comment]
Fine!
