### ISSUE TITLE
[TCOTD2] Performance at the swamp area is abysmal

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#233]
> Is that the best could be done to optimize the swamps, or do you have more work to put in there? For me, the swamp area is the only area in the game where performance is really impacted, with the framerate going down as low as 20 fps.
> 
> (Overall, performance seems better if I'm using OpenGL ES as the backend than the full-featured OpenGL, though the swamps still tank performance using both backends)

Continuing from the discussion at https://github.com/Realm667/Re-Releases/commit/affc708ed8cb672cb04524603f88e50a20a38e0c#commitcomment-129974293

The swamp remains one of the worst performing areas of this map. And the reason why is quite simple.

![image](https://github.com/Realm667/Re-Releases/assets/4926156/970f11fe-f245-4d5c-9520-dda3a4746b24)

In short, the swamp allows line of sight to THREE areas (the small shed, the swamp itself, and the mansion). `stat renderstats` reports about almost 20k vertices being rendered for flats.

![image](https://github.com/Realm667/Re-Releases/assets/4926156/70c31e98-e1b2-4894-ac6f-89aa2a780fca)

Unfortunately the only way to solve this is to rework alter the structure of the map. This is kind of a big job, I did attempt it but I'm simply not good enough to do it (I just destroyed the map by doing it LOL).

Here's my proposed restructure:

![image](https://github.com/Realm667/Re-Releases/assets/4926156/e16bd26d-2766-49dd-99dd-950f91b30d28)

If this is too difficult (to move things, another idea is to simply create some kind of cave or tunnel structure, with doors on both sides (yes, they're needed to cut the views).

![image](https://github.com/Realm667/Re-Releases/assets/4926156/560cf33d-fd4c-4f97-bd7f-a1c481fdf6d1)

@Tormentor667 I hope we can find a solution to this...

**Comment by Tormentor667** [comment]
I have absolutely no performance issues at all so I can't tell how important this is. I'd be okay with the tunnel option though. If you want me to do it, let me know and I will take care of it.

**Comment by nashmuhandes** [comment]
I actually started taking care of this. Maybe that cave suggestion isn't needed. Stay tuned...

**Comment by nashmuhandes** [comment]
Ugh, nevermind. I give up. This is way beyond my skill and patience threshold...

**Comment by Tormentor667** [comment]
Let me know when I can takeover the mapping

**Comment by nashmuhandes** [comment]
@Tormentor667 done, please proceed

**Comment by Tormentor667** [comment]
Picking up the map now and taking care of that area.
