### ISSUE TITLE
[TCOTD2] Inability to access the brain storage secret

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#237]
There's a vent in the brain storage which leads to a secret. To enter the vent, you jump on one of the barrels there. Unfortunately, these barrels are destructible. There's a possibility that they get destroyed during the scripted fight between the cultists and zombies. If that happens, bye-bye secret.

**Comment by Tormentor667** [comment]
Okay, I actually meant it to be like that - so you have to be careful killing the enemies. But if the infighting happens and they destroy the barrels by accident it pretty much sucks

**Comment by nashmuhandes** [comment]
I thought that was by design - basically, a missable secret (secrets are technically not required to complete a level). But yeah, it is janky because the barrels can be destroyed easily.

IMO the bigger problem is that the secret is so obvious and too easily accessible...

**Comment by nashmuhandes** [comment]
Addressed and improved with https://github.com/Realm667/Re-Releases/commit/c2f70e1b6e72af2cd7d6912a83e40b0eb476a3db
