### ISSUE TITLE
[TCOTD2] Was the way to go to the other dimension from the circus meant to be so easy?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#238]
This is something I'm not sure about. Has it always been so easy to just walk a straight line to travel between dimensions in the tent?

I _may_ be remembering things wrongly, and I don't have time to investigate how it was compared to the 2008 version (my memory is really failing me at this point) -- wasn't it that you had to walk the slightly longer way (following the gibs and blood on the floor) to be able to actually access the other dimension? And same goes for traveling back to the real world?

Was this the case before, and somehow some edits broke it? Or was I simply falsely remembering this?

**Comment by Blue-Shadow** [comment]
Yes, it was. There was only one entrance to the tent which also served as the exit, and you had to wind your way through it. Obviously, where you end up depends on where you're coming from.

**Comment by Tormentor667** [comment]
Yes, I can confirm that as well. Some kind of puzzle would definitely fit here.

**Comment by Tormentor667** [comment]
I am okay in recreating the setup from 2008 but I'd suggest making the puzzle even more challenging. Any ideas? Otherwise I'd just try something as soon as the map is free again :)

**Comment by nashmuhandes** [comment]
@Tormentor667 go ahead and edit the .wad, I am done for today

**Comment by Tormentor667** [comment]
Signing in

**Comment by Tormentor667** [comment]
Alright, I am done so far - it's not much harder now but it's in a way I had it imagined almost 20 years ago when I first thought about how this 'trip' could feel.
