### ISSUE TITLE
[TCOTD2] Replace vulgars with zombies at the beginning of the map

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#239]
It's better for pacing, as it's unfair, I feel, for the player to have to deal with enemies at that point that can poison you. The ones in the swamp can remain. Only the ones between the start and the city gates need replacing.

**Comment by nashmuhandes** [comment]
Done with https://github.com/Realm667/Re-Releases/commit/a3acbb4b46cf0ac677794bb3e9928a73e2a0840f
