### ISSUE TITLE
[TCOTD2] The ambush zombie in the house with the diamond

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#240]
There's a zombie that appears in the hallway after you pickup the body armor in the bathroom. It's cheap, to put it bluntly, considering its position and the fact that you don't hear any noise indicating there's something out there. I suggest to either script it to barge into the bedroom or, if that's too difficult to achieve, just remove it entirely.

**Comment by nashmuhandes** [comment]
Done with https://github.com/Realm667/Re-Releases/commit/a3acbb4b46cf0ac677794bb3e9928a73e2a0840f
