### ISSUE TITLE
[TCOTD2] That face on the screen when you get killed by the siren nightmare...

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#241]
... is really, REALLY goofy. I laughed out loud at it. I'm sorry but it's such a terrible idea that tries to be scary but fails horribly. I cannot take it seriously at all, as have all of my friends who helped test it. Can I get rid of it, please. 😂😂😂😂😂

**Comment by Tormentor667** [comment]
Different idea instead? Some kind of shader? Or screen effect?

**Comment by nashmuhandes** [comment]
As much as I absolutely think how ridiculous it is, I have decided to not bother with for this release
