### ISSUE TITLE
[TCOTD2] Spider queen needs testing

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#245]
I've done all I could for the spider boss, in terms of code and assets. I'm unable to fine-tune the gameplay stuff so would appreciate if someone could give her a go and tweak whatever is needed to make the fight better/more balanced. Thanks :)

**Comment by Tormentor667** [comment]
That's a job for @Blue-Shadow I guess :)

**Comment by Blue-Shadow** [comment]
Done my tweaks in b2299dcc7bd3e0fb4b4f99ee4791f46d207dd65f.

**Comment by Tormentor667** [comment]
In my eyes it's perfect now.
