### ISSUE TITLE
[TCOTD2] place another revolver in the mall / move revolver into the mall?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#247]
From my tired testing session, I completely missed (and even forgot) about the pistol at the city gate -- I was running past the zombies and rushing into the city. I imagine some other players may make the same mistake, too

**Comment by Blue-Shadow** [comment]
It should be place it directly in front of the gate, then. My worry, if placed somewhere in the city, is that the player might not wander into where it is right away. Unless guided, how would a player know the [insert place] has a pistol waiting for him or her?

Saying that though, it wouldn't hurt scattering a few revolvers around the place, so no matter where the player goes, there's a good chance he or she will find one.

**Comment by Tormentor667** [comment]
This was mostly the reason why I placed the gun to the camp fire at the very beginning. It's actually impossible to miss it and I don't see a reason to place the pistol later in the city. What benefit do we have from that change?

**Comment by nashmuhandes** [comment]
> This was mostly the reason why I placed the gun to the camp fire at the very beginning. It's actually impossible to miss it and I don't see a reason to place the pistol later in the city. What benefit do we have from that change?

It was because most of the vulgars got replaced by axe zombies in the beginning and it's a bit unfair to front load the pistol so early to the player.

**Comment by Blue-Shadow** [comment]
Yeah, it's not a big deal. It can go back.

**Comment by nashmuhandes** [comment]
Done with https://github.com/Realm667/Re-Releases/commit/d193d4bf80c623d8625b27cf4ab971adc13ee56e
