### ISSUE TITLE
[TCOTD2] Civilian's death

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#248]
After you get rescued by the civilian and leave the shelter, he gets killed by zombies, apparently. However, those zombies, where did they come from? There aren't any zombies' corpses in there to say they came back to life. There also no other means to get into the shelter apart from the door you just used to leave.

**Comment by nashmuhandes** [comment]
Yeah that's a bit of an immersion breaker isn't it. Probably should place a couple of zombie corpses there to make it convincing

**Comment by nashmuhandes** [comment]
Fixed with https://github.com/Realm667/Re-Releases/commit/265b256eccfbb6c4316eab41df42450400d803a2
