### ISSUE TITLE
[TCOTD2] Spider boss's room's door makes incorrect closing sound

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#250]
The sound it makes is the fast closing door sound from Doom.

**Comment by Tormentor667** [comment]
Is it because of its speed?

**Comment by nashmuhandes** [comment]
I'm not sure how to deal with tihs, I have little experience with modifying sounds for the built-in door specials

**Comment by Tormentor667** [comment]
Id simply suggest replacing the fast door sound with the same as for the normal door sound
