### ISSUE TITLE
[TCOTD2] Make spiders drop instead of teleport (spider boss fight)

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#254]
This is probably just me, but I'm not fond of the spiders teleporting into battle. It's too Doom-ish. I feel it'd be better if they dropped from above or something.

**Comment by Tormentor667** [comment]
Good design suggestion, I agree

**Comment by nashmuhandes** [comment]
I moved their spawn points up to the ceiling so they do drop down now, but this is as far as I'm capable of going without creating any more new graphics or assets for it https://github.com/Realm667/Re-Releases/commit/1a778d62b8fa8a45e3bb68129eb89b08513d4446

**Comment by Tormentor667** [comment]
Enough - I just wonder: Are the teleport sounds and the teleport sprites gone as well?

**Comment by nashmuhandes** [comment]
> Enough - I just wonder: Are the teleport sounds and the teleport sprites gone as well?

Yeah I commented out the `TeleportFog` spawn in the script because I assumed when Blue-Shadow said "it felt too Doom-ish", I assumed they'd want the Doom FX removed

**Comment by Tormentor667** [comment]
Perfect!
