### ISSUE TITLE
[TCOTD2] Item count pattern?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#255]
Armor and health bonuses - Yes
Carriable small and large medkits - Yes
Antidotes - Yes

From what I can tell, it's all the restorative items that count towards the item counter. Is this correct, and moreover - intended design?

The reason I'm bringing this up is that it may be quite difficult for players to get 100% items because the carriable health items have a cap of 5 each, on the player, and it's not practical for players to deliberately waste their health items (by using them), just to be able to pick up the abundant medkits lying around. Not to mention, these items are EVERYWHERE and it'd be a chore for a player to track them all down.

**Comment by Tormentor667** [comment]
It is not intended as it is now.

I’d suggest only adding items that can always be picked up.

**Comment by nashmuhandes** [comment]
Changed it so that only hearts and armor bonuses count towards items, therefore being familiar to original Doom's mechanics
