### ISSUE TITLE
[TCotD2] Convert LANGUAGE.TXT into LANGUAGE.CSV for easier localization

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#257]
Is someone able to convert the text file into a table format so it's easier to localize everything? 

Having something like this for BoA was very useful.
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/ef7eb748-b4b5-4c98-afdd-2084be81f877)

**Comment by nashmuhandes** [comment]
Not gonna be by me, sorry.

**Comment by Tormentor667** [comment]
Already took care
