### ISSUE TITLE
[TCotD2] Textcolor of highlighted text in journal

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#258]
I kinda find this color non-fitting
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/2235d993-c14f-4b29-a2e4-70d7fd23eaf8)

Could we turn it into something like this?
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/307af2f4-05c0-40d6-b4b7-ad116f147560)

**Comment by nashmuhandes** [comment]
Done https://github.com/Realm667/Re-Releases/commit/73714cbd62a38fbc71d3c45272189b86868e0041
