### ISSUE TITLE
[TCOTD2] Dogs don't come out to fight the player

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#259]
This seems to have gotten broken. What should happen is, once the boss fight is triggered, the dogs come out of the barn to fight the player. Now they just sit there waiting for the player to enter the barn.

**Comment by nashmuhandes** [comment]
Woops, I did a pass on all of the Thing_Hate scripts in the entire WAD and this must've somehow slipped (probably erroneously assigned the wrong final argument). I'll check later

**Comment by nashmuhandes** [comment]
Fixed https://github.com/Realm667/Re-Releases/commit/64d744d47fb6420285b5b87ef287c0bd55b3cbae
