### ISSUE TITLE
[TCOTD2] The custom small font has only characters for english

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#260]
Just so you guys are aware - translating the text alone is not enough. The small font needs more characters (way way way more) to represent the various non-english characters used.

Just how many, you may be wondering?

This many, maybe: https://github.com/ZDoom/gzdoom/tree/b48caddb96a9fbcde581d4ba31417afe001976bd/wadsrc_extra/static/filter/doom.id/fonts/defsmallfont

It's no small feat. 😅

**Comment by nashmuhandes** [comment]
The hard work comes from trying to take Blue-Shadow's custom font to use as a base, to then add the various accents.

It's manual graphics work that I will say up front, I do not have time to do.

**Comment by Tormentor667** [comment]
I totally missed that. But I wonder - can't the SMALLFONT and BIGFONT forced and in case a character is missing, it simply isn't displayed at all? I ask because german isn't a big deal. The only glyphs that we need here are ä, ö, ü and ß - even I could do that.

**Comment by Tormentor667** [comment]
Well. I actually am able to create the graphics for the missing glyphs, but I have just no idea how to name them and where to place them - or even find out which ones are missing. Any help on that?

**Comment by Tormentor667** [comment]
Small font has been fixed by @Ozymandias81 , only bigfont needs fixes now.
