### ISSUE TITLE
[TCOTD2] Clean up the credits in the `tcotd2.txt` to clearly separate between the legacy and remaster

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#264]
Can you clearly separate the names from the 2007 version versus the 2023 version @Tormentor667

**Comment by Tormentor667** [comment]
Began, but not finished yet I guess 899f182dd3cf5c32cb9fef3ab9e2a3f591c40d50

**Comment by nashmuhandes** [comment]
Yup that's a good start, keep going
