### ISSUE TITLE
[TCOTD2] Thamuz's tentacles' immunity to splash damage

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#265]
One of Blood Thamuz's abilities is that it can spawn tentacles, in a group of four. Unfortunately, due to them being immune to splash damage, the napalm launcher, the explosive weapon that it is, isn't good at clearing them out, which annoys me. Yes, you can switch to the shotgun or Tommy to destroy them, but come on, surely the napalm launcher should be capable of doing that too, right?

**Comment by Tormentor667** [comment]
I agree!

**Comment by Blue-Shadow** [comment]
Done in 3f842ece4c9ce75a6e3c842db5bad5e2eae69ea6.
