### ISSUE TITLE
[TCOTD2] Doom Thamuz lacks death special effects

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#266]
... you know, like the ones Blood Thamuz has.

**Comment by Tormentor667** [comment]
@Ozymandias81 same here :)

**Comment by Tormentor667** [comment]
@Blue-Shadow isnt that fixed with your Thamuz rework?

**Comment by Ozymandias81** [comment]
It was intentionally simplicistic in Bloom, to mimic CyberDemon original death sequence (while also Tchernobog in Bloom dies in a similar way seen in Blood, for consistency).
