### ISSUE TITLE
[TCOTD2] Old `credit.jpg` is outdated

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#270]
This screen appears when you press F1 on the main menu (but _not_ in-game; remember the F1 key in-game has already been hijacked to show the journal instead).

I suggest replacing the info on that page with something more helpful, like gameplay tips or something.

**Comment by Tormentor667** [comment]
Fixed with 5eb4d893ab5d86d46af70f7f6b1862ca27221f8c
