### ISSUE TITLE
[TCOTD2] Please upload the PSDs for the various graphics (help, credits etc)

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#274]

**Comment by Tormentor667** [comment]
They are already online, check the graphics folder

**Comment by nashmuhandes** [comment]
> They are already online, check the graphics folder

No, they aren't. You have .psd inside `.gitignore` and it's only visible on your computer.

I'm on a computer far away from home and the PSDs aren't in there
