### ISSUE TITLE
[TCTOD2] Don't hide HUD if options menu is open

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#276]
The reason I suggest this is because otherwise it makes it more of a hassle to see the results of changing settings related to the HUD, as you have to close the options menu to be able to see that.

Could hiding the HUD be restricted to in-game menus?

**Comment by Tormentor667** [comment]
Yes that makes sense actually

**Comment by nashmuhandes** [comment]
Can do

**Comment by nashmuhandes** [comment]
Done with https://github.com/Realm667/Re-Releases/commit/7e7d1882069fcc4ba06b76dc7bec27d472b5ca91
