### ISSUE TITLE
[TCOTD2] Final polishments to assets

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/Re-Releases#278]
- [x] Since we are using glyphs and externalized language entries for all menues and such (except for the CONFONT, but that's not a problem I think), we should get rid of the old graphics replacements inside [Menu folder](https://github.com/Realm667/Re-Releases/tree/master/tcotd2/graphics/menu). Should we, or keep them for legacy reasons?

- [x] Also there are 3 missing sounds if I dump Soundlist from console, wonder if those are just put for the sake to alternate silence between present random sounds or if they are definitely something needed. Here you are said sounds:

world/sludgegloop
sfx/explosion1
thamuzdoom/death2

Are these needed?

- [x] One last note: if you use developer 8, you can notice that after a while you start the game, CircusTarget1Wrap and 2Wrap scripts gets triggered on/off continuously by someone, maybe tommygun cultists, on lines 4430 and 4393 @nashmuhandes . Not that's so crazily important, but just bringing this to attention in case something hasn't been noticed

**Comment by nashmuhandes** [comment]
About the running scripts at the circus:

That script is related to the minigame at the circus where you get to shoot the targets. The script gets called when one of the targets touches the edge of the room. Naturally, the scripts will keep retriggering until all targets are destroyed.

The scripts simply only have one instruction (it calls SetActorPosition) which is hardly any performance cost, so this is nothing to worry about.

**Comment by nashmuhandes** [comment]
Took care of the old menu graphics, and the script thing technically is [Won't change] (it's performance impact is far too minimal)

That leaves the extra 3 sounds thing. Unfortunately I'm not sure what do do here, so someone else will have to take care of it.
