### ISSUE TITLE
[TCOTD2] Alt HUD still uses Doom font?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#279]
![image](https://github.com/Realm667/Re-Releases/assets/4926156/54e36c18-8bb4-4848-ae39-7c64d1de59d9)

@Blue-Shadow can you take a look? My experience working with the Alt HUD code is very tiny X)

**Comment by Tormentor667** [comment]
Ugh... the althud... I'd wish we could simply disable it...

**Comment by Blue-Shadow** [comment]
> Ugh... the althud... I'd wish we could simply disable it...

No! That's Graf's baby. We can't do that :P (not that we could if we wanted to).

**Comment by Blue-Shadow** [comment]
Font changed in 9fc4a8de0ac486f53bc9fc4bffcae32f93918df1.
