### ISSUE TITLE
[TCOTD2] Obituary message when killed by the guillotine 

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#282]
Currently, it just says "[player] died.", which is a bit boring.

**Comment by nashmuhandes** [comment]
Same dealio as the other thread about the HUD counter swap -- no objections, I just simply don't have any computer time today (taking care of IRL stuff for most of the day until night), sorry!

**Comment by Blue-Shadow** [comment]
I may not have enough time to do this myself. Besides, I don't have experience with the spread-sheet LANGUAGE thing.

It's not massively important. It can be left for a 2.0.1 or 2.1 release.

**Comment by Tormentor667** [comment]
I did it (most propably) a36544d86487fb117cf6725e83ef1e9924bcf630
