### ISSUE TITLE
[TCOTD2] Add the health-and-armor swap option to menu

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#283]
This is in reference to [this](https://github.com/Realm667/Re-Releases/commit/03a7aa7521995ffc45ff8a68fecd95a53ff333b9).

**Comment by nashmuhandes** [comment]
@Blue-Shadow I don't mind at all but, sorry, but I'm unavailable to edit this today, and I think the release is like 10 hours from the time of this message -- think you can sneak it in? Also probably need to somehow get the german and italian translation in as well. Also also, you'll need to figure out where it goes in terms of the menu layout/categorization

**Comment by Tormentor667** [comment]
It's up to you if you want to have it, I am okay with having it in but also leaving it out.

**Comment by Blue-Shadow** [comment]
It can be left for another time. It's not a necessity right now.
