### ISSUE TITLE
[TCOTD2] Secret counter is now broken

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#285]
![image](https://github.com/Realm667/Re-Releases/assets/4926156/a3eb9d78-8efc-45a9-87d4-10a6ed362836)

UDB reports 12 secrets and it indeed used to be that 100% of the secrets can be found.

Now the counter shows 21 secrets. I have no idea where these extra numbers are coming from.

This should be fixed ASAP because otherwise this breaks 100% secrets for players.

**Comment by nashmuhandes** [comment]
![image](https://github.com/Realm667/Re-Releases/assets/4926156/728a91f9-7a39-4e51-905b-a6d9f5a37cd0)

Dammit Torm :P

**Comment by Tormentor667** [comment]
Ugh.... me = idiot! Thanks for noticing!
