### ISSUE TITLE
[TCotD2] Dog Boss fight suggestion (Nash)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#29]
> Dog boss fight proposal:
> 
> It has always bothered me that there is no warning to the dog boss fight. It's very easy to accidentally stumble into the barn with barely any weapons and ammo, and just get fucked.
> 
> So I propose the barn be locked with a key. Finding the key will give you a chance to do some adventuring and gather weapons and ammo - perhaps the key should be available only after getting the shotgun?
> 
> Once the key is acquired, when opening the barn door - a short cutscene plays (last chance for player to prepare).
> 
> (Cutscene can be skipped)
> 
> Here's how the cutscene must play:
> 
> - Player walks to the barn door to open it
> - Startled by dogs suddenly lashing out the door, drops the key
> - Player tries to reach the key, but one of the dogs eats it
> - Player runs to the center of town (where Thamuz' summon spot is)
> - Mysterious cultist suddenly appears (possibly the dogs' caretaker), locks the barn door
> - Cultist points to the player, telling the dogs to attack, before casually walking offscreen
> - Dogs give a huge roar to the player. Boss battle begins.
> - All players will be teleported together.
> 
> When the last dog is killed, the barn key will spawn out of the last dog's corpse. This forces the battle to be cleared properly.
> 
> The reason I want to lock the dog battle here is I don't want players skipping the dogs to get the moon key and sequence-break things. I would rather not have the dogs alive by the time the first nightmare is encountered.
> 
> * I will be adding a cutscene system where I am able to author camera animations in Blender and the export the result to something GZDoom can playback. Don't worry about this detail.

**Comment by nashmuhandes** [comment]
While I won't be doing the "locked door" idea, I still firmly believe it is unfair because it's possible for a starting player with nothing but the pistol and a few rounds of ammo, to accidentally stumble into the dog barn.

Instead, how about - only spawn the dogs (and allow the fight activation trigger script) AFTER picking up the shotgun?

Could do something like:

1) player picks up the shotgun
2) play some dog noises (howling/growling?)
3) print message to the player (and add to the journal, when that system is impleted), "I hear howling in the distance... seems have come from the city center. Perhaps I should investigate it."

**Comment by Tormentor667** [comment]
That could work but on the other hand, what happens if the player enters the barn before picking up the shotgun and spawning the dogs? Maybe close the barn doors? And add some kind of "Beware of the dogs" sign as a special hint so the player remembers this area and can combine the dogs, the sounds and the hint?

**Comment by nashmuhandes** [comment]
Torm, we're no longer using the barn door idea. :P

Currently, a cutscene triggers as you approach the dog area.

What I am proposing here, is that - do not spawn the dogs (and therefore trigger the cutscene, then starting the boss fight) until AFTER the player has the shotgun.

**Comment by Blue-Shadow** [comment]
Where would the dogs spawn? Inside the barn?

**Comment by nashmuhandes** [comment]
I'll just close this thread, seems like people are missing my comment that the OP idea is no longer being used. :P
