### ISSUE TITLE
[TNTx] Alternative death of Demon doesn't show his arm dropping off

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#298]
It works in Austerity, Sapphire, TCotD1, Refinery but it does not work in TNT1, TNT2, TNT3 and TNTLE. The sprites are in the right folders but the actor isn't appearing somehow. @Ozymandias81 any idea?

![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/49d996e6-78fb-437f-b549-e58954ad5f3c)

**Comment by Ozymandias81** [comment]
I am gonna check this asap, there was a change on the name itself and the death state of the actor to let it work
