### ISSUE TITLE
[KDiZD] Startup warnings in several of the maps

### ISSUE THREAD

**Issue by ioan-chera** [Realm667/Re-Releases#3]
Several maps of KDiZD have errors shown in console when you start them; for example Z1M4. They seem to be about giving invalid arguments for linedef specials. Unless GZDoom is smart about it, I think it would be best to fix those arguments, because they might break future GZDoom versions which add functionality to them.

**Comment by Ozymandias81** [comment]
Which version of gzdoom are you using? I did my recent fixes with 4.4r948
