### ISSUE TITLE
[TCotD2] Nash's Tasklist

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#30]
> Here are the things that I am self-assigning to do (in other words, don't get in my way ;))
> 
> - [ ] General visual/aesthetics goal: I want to make every asset look like they belong natively in Blood. That means higher res sprites, authored in the Blood palette, square aspect ratio
> - [x] Bring back Blood-paletted sprites for as many of the actors as possible (the zombies, cultists, gore/dead bodies etc)
> - [ ] Replace Daggerfall decorations with original recreations (using my visual goals as a guide). They look horribly out of place in this project
> - [ ] Overhaul combat both visually and audio-wise. I will be smoothing out the weapon animations, adding visual eye candy like bullet casings and particle effects. The weapons will feel more impactful BUT you are still not a overpowered heavy metal bad-ass like the Doomguy. Survival horror element from original TCOTD2 will be preserved.
> - [x] Import a customized version of NashGore Vengeance Edition specially adjusted for TCOTD2.
> - [x] Add an immersive way to keep track of when the next nightmare siren will happen. Not sure about the details yet. Done
> - [x] Add the additional widgets (pendant and oil lamp meter) into GZ's AltHud
> - [ ] Completely redesign the nightmare monster. I am taking Pyramid Head as a visual inspiration.
> - [ ] Change the nightmare encounter so that only 1 nightmare will spawn close to each player. Possibly have the nightmare be accompanied by smaller enemies. The nightmare monster itself may be temporarily incapacitated.
> - [ ] Redesign the church boss. The Heretic Apprentice looks out of place. I will come up with something fitting the game's mood and artwork.
> - [x] Redesign Thamuz. It has to be an absolutely menacing boss fight. No design idea yet as to how it'll look visually.
> - [ ] Redesign the player sprites. Make him look something like a cross between Caleb and BJ.
> - [ ] Add a journal menu. In the journal, you can view previously-read letters and also review quest objectives.
> - [ ] Add real-time updating objectives for the various events that happen in the adventure. Things like "Investigate the graveyard", "Learn how to summon Thamuz", etc. It will be a very simple objective system.
> - [ ] Add a scoring mechanic to the game where you will be ranked at the end of the adventure, similar to the Resident Evil games. Keep track of stats like total time, kills and secrets, how many letters read, how much health lost, how many shots hit, etc.
> - [x] Implement a better snow spawning system Done
> - [ ] Finalize ambient sound system
> - [x] Merge customized versions of SpriteShadows, Tilt++ and WeaponSway (these will all have adjustments unique to TCOTD2 that aren't available in the public/universal versions of said mods) Done
> 
> This may seem like an insane amount of work but these are all actually do-able for me. Most of the code-related tasks already have existing code I have written over the years that I can just import those into the project. The most time spent would be creating the new sprites, but even those aren't impossible - I have a lot of experience making custom new sprite sets . 

@nashmuhandes

**Comment by Tormentor667** [comment]
@nashmuhandes it has been a while since this issue, so I wonder: Still interested? We are doing heavy progress lately and I am looking forward to a release soon - any of the suggested points here would be nice to have!

**Comment by nashmuhandes** [comment]
@Tormentor667 I will have to scale back the scope of my ambitions here as when I initially joined the project, it was a much different time where I was not as busy as I am now. I will go over these and see which ones I can quickly implement

**Comment by Tormentor667** [comment]
Looking forward to that, make sure to update your repo, a lot has been improved and added in the past months :)

**Comment by Blue-Shadow** [comment]
What I want to see implemented is the ability to read the files/letters more easily, because some of them (the handwritten ones, especially) are a little difficult to read.

**Comment by nashmuhandes** [comment]
I am thinking of doing the Resident Evil thing where the text is in actual text form (plus it will then allow localization). It would require a rework of the graphics assets to remove the readable text, though.

![image](https://user-images.githubusercontent.com/4926156/211490293-5f5a19b4-86ce-4477-b722-e16c2ecb1809.png)

**Comment by Blue-Shadow** [comment]
Yeah, I was thinking the same.

**Comment by Tormentor667** [comment]
The new system might be cool but to a certain extent I’d be happy to have the notes still in. I think they are extending the atmosphere a lot

**Comment by nashmuhandes** [comment]
Another way to keep both is - have the graphic-based letters stay, but upon clicking on them, the actual text (localizable) gets copied into your personal journal, that you can pull up and read any time.

**Comment by Tormentor667** [comment]
I like that approach :)

**Comment by Ozymandias81** [comment]
Thamuz has been replaced with Cyberbog, so I put it done

**Comment by nashmuhandes** [comment]
Closing this thread as it's too outdated and doesn't align with my availability anymore

**Comment by Tormentor667** [comment]
What final plans do you currently have for the mod?

**Comment by nashmuhandes** [comment]
> What final plans do you currently have for the mod?

Objective system, ZScript cleanup, code optimization, plus a few other small tasks

**Comment by Tormentor667** [comment]
M

**Comment by Tormentor667** [comment]
Reasonable enough :)
