### ISSUE TITLE
[ZPack] Finalizing E2 by finetuning E2M2 and E2M6

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#307]
Currently E2 seems fine to me so far, except M3 and M6 which are not in the same visual style as the rest. I will take care of them personally. This is just my reminder issue.

- [x] E2M2
- [x] E2M6

**Comment by Ozymandias81** [comment]
Do you mean E2M3 or E2M5? Remember that we can't edit E2M5 scripts @Tormentor667

**Comment by Tormentor667** [comment]
Nope, I mean M6 :)

**Comment by Tormentor667** [comment]
E2M2 is done, onto E2M6

**Comment by Tormentor667** [comment]
...and E2M6 is a mess visually - and in terms of gameplay, sorry, I have to say this. I would rather remove it before improving it... but let's see.

**Comment by Tormentor667** [comment]
We are almost done :)
