### ISSUE TITLE
[Stronghold] Scripts

### ISSUE THREAD

**Issue by RichardDS90** [Realm667/Re-Releases#36]
- [x] The map scripts for some odd reason aren't being compiled in the editor. Is there any solutions for this?

- [x] And moreover, the pistol loading animation is happening during the briefing.

**Comment by Ozymandias81** [comment]
Map script solved with [this commit](https://github.com/Realm667/Re-Releases/commit/f6699d6fbf29d9402ccd010d09d03ab81224c52b)

**Comment by Ozymandias81** [comment]
And solved the reloading sound with [this commit](https://github.com/Realm667/Re-Releases/commit/b4cca0f9e07128f8640ae841054bdb2af579b299) too.

**Comment by Tormentor667** [comment]
Thanks for the fixes!
