### ISSUE TITLE
[ZPack] E2M2 & E2M0

### ISSUE THREAD

**Issue by RichardDS90** [Realm667/Re-Releases#38]
Hey Dan. In regards to those two maps, will they be recieveing the same treatment that you gave E1M2? Because looking at the two maps, they do feel pretty subpar. If you are planning to, when I get up to their slots in the order, I will skip them over and do them last.

**Comment by Tormentor667** [comment]
Yes, most propably. I am currently taking a break because we are getting a new kitchen and we need to remove the old one before we can place the new one. After that I will check E1 again and then continue on E2.

**Comment by RichardDS90** [comment]
No worries. Is there a rough time on when you'll be back in action?

**Comment by Tormentor667** [comment]
From now on - highly motivated
