### ISSUE TITLE
[ZPack] E2M5 has no way of editing the script.

### ISSUE THREAD

**Issue by RichardDS90** [Realm667/Re-Releases#39]
What would we need to do to have the script to be edited so I can get rid of redundant scripts like panning floors, sector colours, etc?

**Comment by farlowj** [comment]
Let me check later today for the original script, as this was my original submission.  Though I believe Vader had done some touch ups before release.

**Comment by farlowj** [comment]
Welp, bit more than a day later, I don't have the original script.  Was lost several hard drive formats ago.

**Comment by Tormentor667** [comment]
Wasn't there a software on ZDoom.org which could decompile ACS?

**Comment by RichardDS90** [comment]
There's absolutely no rush, or no need if it's going to be too much, I don't need to edit any of the scripting with how the level works, it's just for getting rid of floor panning scripts and all that.

**Comment by Tormentor667** [comment]
@RichardDS90 you might want to check this: https://forum.zdoom.org/viewtopic.php?f=122&t=74130&p=1208054#p1208054

**Comment by Ozymandias81** [comment]
Since this is not very important, I am gonna close it.
