### ISSUE TITLE
[KDiZD] Add -fast speeds to monsters

### ISSUE THREAD

**Issue by ioan-chera** [Realm667/Re-Releases#4]
Unless the current state was a conscious design decision, maybe it would help if you add -fast and nightmare speeds to the new KDiZD monsters and projectiles, wherever suitable. Right now only the stock Doom monsters have their speeds increased, resulting in inferior stats for the KDiZD monsters when playing on -fast (for example the blood demons become slower than the pinky demons, despite being supposed to be faster).

**Comment by Ozymandias81** [comment]
Addressed, something I'll work on at later stage

**Comment by Tormentor667** [comment]
Good point, this is worth being considered.
