### ISSUE TITLE
[Refinery] Plans

### ISSUE THREAD

**Issue by RichardDS90** [Realm667/Re-Releases#40]
Hiya @Tormentor667 , what is the plan exactly for the Refinery Remaster? I fancy have a slow crack at it at some point.

**Comment by Tormentor667** [comment]
Currently one of the important things is refining the difficulty levels. Other than that, adding dynamic lights where appropriate and make graphics widescreen compatible

**Comment by RichardDS90** [comment]
I can definitely do the lights for sure. As for the difficulties, what do you have in mind?

**Comment by Tormentor667** [comment]
Then feel free to, we just need to add the appropriate light actors before you can add them.

Regarding the difficulty: People complained about the map that it is too hard - I think we need to do something about it, make it a bit easier or deliver a bit more ammo.

**Comment by RichardDS90** [comment]
I'll do the difficulty last, and will make a backup of the pre difficulty change in case we need to revert to any part. 

Also while I'm at it, in regards to the light ray textures, will they be staying or will it be a case of changing them to the actors?

**Comment by Tormentor667** [comment]
Regarding the difficulty, just be careful: The game has two difficulty settings, one as standard and the second one as "game plus" if you replay the map after finishing it one time. 

Regarding the light-ray-textures: Same procedure as in ZPack :)

**Comment by RichardDS90** [comment]
I've taken the new game plus into account when sorting difficulties.

So basically I replace the light ray textures as the light ray actor instead, am I right?

**Comment by Tormentor667** [comment]
Perfectly correct :)
