### ISSUE TITLE
Swarm sprite changes.

### ISSUE THREAD

**Issue by RichardDS90** [Realm667/Re-Releases#46]
Should we change the sprites of the Swarm to something a bit more detailed? There's a few sprites on the repository we could use in it's place.

**Comment by Tormentor667** [comment]
For the Refinery? What do you have in mind?

**Comment by RichardDS90** [comment]
Well the Swarm Spawner sprites in the special FX section look far better and is just as fitting, and considering it would be used in a similar purpose, might as well use those sprites.

**Comment by Tormentor667** [comment]
I agreem let's go for it :)
