### ISSUE TITLE
[TheRefinery] Portal isn't working

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#48]
I wonder why we do get that error message, the portal seems to be set up correctly?
![grafik](https://user-images.githubusercontent.com/10298439/147879898-707ca672-b7fb-4056-b2c1-54b67973cd13.png)

**Comment by RichardDS90** [comment]
Reverted to sprite based portal with this particular one. Will close.

**Comment by Tormentor667** [comment]
Thank you!
