### ISSUE TITLE
[ZPack] Needs terrain liquid splashes

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#49]
@Ozymandias81 do you think you can add these?

**Comment by Ozymandias81** [comment]
I'll check when I can

**Comment by Tormentor667** [comment]
Awesome thank you :)

**Comment by Ozymandias81** [comment]
I think most of them are implemented already, let's see. I remember there was a problem with blood based ones.

**Comment by Ozymandias81** [comment]
Implemented most of them, still need to understand why Blood based ones doesn't work yet (same on refinery)

**Comment by Tormentor667** [comment]
Well done, but no idea what's wrong with the blood one... have you a clue?

**Comment by Ozymandias81** [comment]
It has been already fix, there where some typos on its definitions

**Comment by Tormentor667** [comment]
Thank you!
