### ISSUE TITLE
Updated names for credits

### ISSUE THREAD

**Issue by esselfortium** [Realm667/Re-Releases#5]
Can you please update my name to Sarah Mancuso in credits.txt and in credit11.png? Should probably also update Marisa Heit's name while you're at it. Thank you!

As a related aside, I've always been unsure why I'm credited for secondary mapping and quality control on z1m1 -- the extent of my involvement was editing some rocks and the shotgun room for 1.1, and had nothing to do with the map's creation otherwise. That'd be tertiary at most, surely...?

**Comment by Tormentor667** [comment]
No problem about this, I will take care and commit the changes.
