### ISSUE TITLE
[ZPack] E1M8/E1M9 Doors are not playing a sound sequence anymore

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#50]
Mostly these type of doors:
![grafik](https://user-images.githubusercontent.com/10298439/155852658-442967b7-5b8f-4b40-ba29-25491b4cd45a.png)

No open or close sound is being played at all.

**Comment by RichardDS90** [comment]
Issue has been resolved by the floor Z Height not being the same as the sectors that use them.
