### ISSUE TITLE
[ZPack] Nashgore blood is not affected by gravity if a floor is lowered

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#56]
![grafik](https://user-images.githubusercontent.com/10298439/157506152-6e7437e6-cc76-4a9c-a882-a2fad831a7a2.png)

**Comment by Ozymandias81** [comment]
Applied MOVEWITHSECTOR flag, even if they also have NOBLOCKMAP in certain circumstances. Let me know if it works now (don't know which map is that to test with)

**Comment by RichardDS90** [comment]
Confirmed to be working perfectly.
