### ISSUE TITLE
[ZPack] Skullkey hud offsets are wrong

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#57]
![grafik](https://user-images.githubusercontent.com/10298439/157514665-20e822bd-6df7-4e72-9b1f-e038d9ba1a26.png)

**Comment by Tormentor667** [comment]
I wonder, is it wrong on othert Re-Releases as well?

**Comment by Ozymandias81** [comment]
I will check :+1:

**Comment by Tormentor667** [comment]
Thank you :)

**Comment by Ozymandias81** [comment]
Apparently only TCOTD1 had as issue with stkeys6 graphic on its sbarinfo definition, should have been 29 instead of 27 its offset codewise. Tested all others, they work fine.

**Comment by Tormentor667** [comment]
Thanks kindly for checking that!
