### ISSUE TITLE
[TCotD2] Not all exclamation marks get activated on nearing them (radius too little?)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#59]
Not all exclamation marks get activated on nearing them. Is the radius too small for activation @Ozymandias81 ?

**Comment by Ozymandias81** [comment]
Some are placed Dormant with tags on map, check tags 25, 31 and 40. Just enlarged a bit their radius (gets doubled on builder).

**Comment by Tormentor667** [comment]
That's fine, these need to be dormant as they are only visible when you read the right letters.
