### ISSUE TITLE
[TCotD2] Adjust final boss battle (Thamuz)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#63]
Maybe make the arena more green and make sure to add gldef lights to the boss dying sequence.

**Comment by Ozymandias81** [comment]
What about adding instead a different boss, less Doomish but more Bloodish? @Tormentor667 

![image](https://user-images.githubusercontent.com/11136108/204306251-90abe2b3-e4e1-4a28-96d2-f1a3e40ae264.png)

**Comment by Tormentor667** [comment]
Yes, that looks nice indeed!

**Comment by Ozymandias81** [comment]
While I did not test in game, my bosses are ready for the purpose @Tormentor667 @nashmuhandes @RichardDS90

**Comment by nashmuhandes** [comment]
> While I did not test in game, my bosses are ready for the purpose @Tormentor667 @nashmuhandes @RichardDS90

sure thing. what do you need me to do?

**Comment by Tormentor667** [comment]
Improve the battle I guess... it's still... well, dull?

**Comment by Ozymandias81** [comment]
Both bosses have cool effects and various attacks, the experience and fight between them should really differ between chosen paths... though maybe some stuff happening and an healthbar indicator maybe would be the piece of cake.

**Comment by Tormentor667** [comment]
@nashmuhandes how good are the chances that we get this sorted? Is it even needed?

**Comment by nashmuhandes** [comment]
Sorry, I won't have enough time and resources to tweak the final boss. Someone else will have to come with some better ideas...

**Comment by Tormentor667** [comment]
@Ozymandias81 didn't you want to do something about it?

**Comment by Ozymandias81** [comment]
I think it is good enough with the sheer amount of things we have put for both bosses, and spritewise it would be too complicate to edit on my end (if any find something that should be changed, not me). So I am done with these bosses.

**Comment by nashmuhandes** [comment]
Let's just wrap it up for now. We are running out of time already. XP
