### ISSUE TITLE
[TCotD2] Replace some sprites with 3D models?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#65]
I wonder, would it make sense to replace some sprites with 3d models from Blade of Agony @Ozymandias81 ?

**Comment by Ozymandias81** [comment]
Imagine using 3d trees and their impact on performance... I don't think it would be wise.

**Comment by Tormentor667** [comment]
We had been using more trees in Blade of Agony ;)

**Comment by Ozymandias81** [comment]
Beside the voxels I have put for lights (which still must fix behavior wise for on/off as I did for BoA), I don't plan to put models for this mod.
