### ISSUE TITLE
[TCotD2] Ventalation grates not changing into a destroyed texture when hit.

### ISSUE THREAD

**Issue by RichardDS90** [Realm667/Re-Releases#66]
![Screenshot_Doom_20221124_175013](https://user-images.githubusercontent.com/86927935/203847129-5ba91a17-abbe-4c56-9e84-ccf49b40cd91.png)

**Comment by RichardDS90** [comment]
It does still allow it to be walked through when hit however.

**Comment by Tormentor667** [comment]
Found the issue and fixed it :)
