### ISSUE TITLE
[TCotD2] End music is missing

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#70]
![grafik](https://user-images.githubusercontent.com/10298439/205131921-3b9839e3-175f-4054-a100-373e2fc735ee.png)

**Comment by Ozymandias81** [comment]
It is something I am already aware and it happens when you die, I need to tweak the code to have diff music for normal death and vs Siren.

**Comment by Tormentor667** [comment]
Should be fixed already
