### ISSUE TITLE
[TCotD2] AI upscale for texturesd (poll)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#71]
Generally I am not a big fan of AI-upscales of textures but the grungy look of Blood's original textures is destined to be upscaled somehow as the results are very convincing. What do you think?

![Screenshot_Doom_20221218_143608](https://user-images.githubusercontent.com/10298439/208301459-dbf5cf1a-4e82-494f-895d-bb6618a20750.png)
![Screenshot_Doom_20221218_143618](https://user-images.githubusercontent.com/10298439/208301463-433a7e41-aa16-4f1e-b9a0-d79251a789f0.png)
![Screenshot_Doom_20221218_143635](https://user-images.githubusercontent.com/10298439/208301464-7bd88715-30bf-4918-b9b6-96b81634b7d0.png)
![Screenshot_Doom_20221218_143645](https://user-images.githubusercontent.com/10298439/208301466-2ccbfc5c-5ab1-4347-980e-d6b3cfb74be2.png)
![Screenshot_Doom_20221218_143702](https://user-images.githubusercontent.com/10298439/208301467-f406e1a6-26a9-40af-b492-ea36fbf2e629.png)
![Screenshot_Doom_20221218_143709](https://user-images.githubusercontent.com/10298439/208301469-f6fba379-f4a2-426d-bd91-28954c3c365e.png)
![Screenshot_Doom_20221218_143713](https://user-images.githubusercontent.com/10298439/208301471-3dd156d6-201e-4f92-8811-7d1a0fcec1ef.png)
![Screenshot_Doom_20221218_143728](https://user-images.githubusercontent.com/10298439/208301474-71f5b5d6-a574-4702-8682-0cd2821a1a87.png)

**Comment by Tormentor667** [comment]
The problem will be renaming all the textures to the TCotD2 names... but the pack is brilliant.

**Comment by Tormentor667** [comment]
Added, can be improved by interest @Ozymandias81

**Comment by Ozymandias81** [comment]
Upscaled tx have lots of seams, I think it is better to stitch original ones and strip down instead doubles to reduce final filesize of the mod #84
