### ISSUE TITLE
[TCotD2] Firespawner drops dynamic light but if inactive doesn't remove it

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#73]
![grafik](https://user-images.githubusercontent.com/10298439/211211507-8b2b8811-a5d5-478d-b2b1-4db86a568500.png)

**Comment by Blue-Shadow** [comment]
Fixed in f5d4edd3841d450c5ba02d895ed9dc8dd641495e

The problem was the fire spawner spawned two light actors of which only one was removed.
