### ISSUE TITLE
[TCOTD2] Texture misalignment

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#75]
It's on both sides of the main door of the grocery.

![Screenshot_Doom_20230110_034616](https://user-images.githubusercontent.com/4287687/211444180-57a735df-990e-4671-acc5-f6bcc770a4e6.png)

**Comment by Ozymandias81** [comment]
It still exist also without upscaled tx, gonna fix
![Screenshot_Doom_20230111_133556](https://user-images.githubusercontent.com/11136108/211807993-6a5c4532-9a4d-47e3-8db1-1a19b3bf7500.png)

**Comment by nashmuhandes** [comment]
Fixed
