### ISSUE TITLE
[TCOTD2] Air shaft opening has the wrong texture

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#76]
The air shaft opening you see in the screenshot below needs to be destroyed in order to pass through. The issue is, it's using the wrong texture, the one where it shows that it's already destroyed.

![Screenshot_Doom_20230110_034913](https://user-images.githubusercontent.com/4287687/211445001-f890f9cc-127b-4fbc-8176-9ab661c154f4.png)

**Comment by nashmuhandes** [comment]
Fixed
