### ISSUE TITLE
[TCOTD2] Weird green flickering light in the "courtyard"

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#78]
... or whatever the area is called.

I'm not quite sure if it's intentional, but I find it weird (and a little annoying) to be there.

![Screenshot_Doom_20230110_035855](https://user-images.githubusercontent.com/4287687/211445742-c778c506-0e63-4a78-9082-771669f342b1.png)

**Comment by Tormentor667** [comment]
That should be inactive, need to fix

**Comment by nashmuhandes** [comment]
I think I fixed it - all I had to do was tick the "dormant" flag on the dynamic light tagged 165, right? @Tormentor667

**Comment by Tormentor667** [comment]
Exactly, thank you!
