### ISSUE TITLE
[TCOTD2] Strange window texture

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#79]
![Screenshot_Doom_20230110_082448](https://user-images.githubusercontent.com/4287687/211531443-2d23241f-ee11-476b-8753-e974fec19f05.png)

**Comment by Ozymandias81** [comment]
This because of the hires replacements mentioned on #84

**Comment by Ozymandias81** [comment]
Can confirm, without upscaled looks fine
![Uploading Screenshot_Doom_20230111_133739.png…]()

**Comment by nashmuhandes** [comment]
Fixed
