### ISSUE TITLE
[TCOTD] A hanged corpse sinking in the floor

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#8]
This corpse should probably be replaced with something shorter that doesn't sink into the floor.

![bug3](https://user-images.githubusercontent.com/4287687/88257130-c3927380-ccc5-11ea-9ccb-a7c97e39bf9d.png)

**Comment by Tormentor667** [comment]
Thanks for all the reports @Blue-Shadow and for all the fixes @Ozymandias81 - this will definitely improve the experience!
