### ISSUE TITLE
[TCOTD2] texture misalignments in the cistern (there's a lot!)

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#80]
![Screenshot_Doom_20230110_192044](https://user-images.githubusercontent.com/4926156/211540756-ff052bcb-692d-444d-91d4-3efc827c960e.png)

![Screenshot_Doom_20230110_192245](https://user-images.githubusercontent.com/4926156/211540785-884fe142-93c0-437a-a142-393c51bbc61e.png)

![Screenshot_Doom_20230110_192601](https://user-images.githubusercontent.com/4926156/211540814-d7b4cceb-4ac9-4390-a743-59eecf4dedcf.png)

![Screenshot_Doom_20230110_192417](https://user-images.githubusercontent.com/4926156/211540805-fd088b29-dbf3-4062-aff1-ce94877e1b2b.png)

![Screenshot_Doom_20230110_192413](https://user-images.githubusercontent.com/4926156/211540796-383a5afe-3109-427f-b7d6-6f12a585a316.png)

**Comment by Ozymandias81** [comment]
Looks better without upscaled though
![Screenshot_Doom_20230111_134125](https://user-images.githubusercontent.com/11136108/211809021-4f2f304d-6240-46d5-9ef8-999c2dfaf2aa.png)

**Comment by nashmuhandes** [comment]
Fixed
