### ISSUE TITLE
[TCOTD2] Fist is useless, I propose the pitchfork be available from the beginning

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#83]
There really isn't any situation where the fist is preferable.

Streamlining the weapons would keep the combat satisfying

**Comment by Tormentor667** [comment]
I’d keep the fists for a reason: Imagine throwing the pitchfork somewhere where you can’t recover it. That’s the reason why we have more than one pitchfork in the map.

**Comment by nashmuhandes** [comment]
Oh LOL, I forgot the pitchfork can be thrown. :P
