### ISSUE TITLE
[TCotD2] Cistern needs a lot of map fixes

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#87]
But I will wait for the hires pack to be removed first before proceeding. Attempting to do any mapping work, especially concerning texture alignment, while the hires textures are still in the repo, is a recipe for disaster

**Comment by Tormentor667** [comment]
Well, if it is really not helping anything, we can remove the hires textures for now. No need to force them in (at least keep the hires skybox though ;))

**Comment by nashmuhandes** [comment]
Did a pass on the cistern. Had to clean up some mapping errors. Will continue to improve it a bit more before I close this thread.

Actually there's only one thing I'd like to do, for now - replace those slabs of stones with a climb-able ladder. Not a fan of platforming in this area.

**Comment by Blue-Shadow** [comment]
I was testing this area yesterday, and I do agree about platforming. I also wasn't able to get out of the cistern, as I couldn't climb up to the third lever, so I had to cheat to get out of there.

**Comment by nashmuhandes** [comment]
Got rid of the stone slabs and replaced it with a ladder.

**Comment by nashmuhandes** [comment]
Cistern improvement ideas to make it feel more complete:

- Needs running water ambience. It's too quiet down there
- Disgusting props like floating human waste or gibs in the water

**Comment by Tormentor667** [comment]
Good point, it would fit good to the actual story behind the cistern.

**Comment by Tormentor667** [comment]
Added a proper soundscape to the area. Is someone interested in adding human waste and gibs? I am not the best spriter so this is something for @nashmuhandes propably.

**Comment by Blue-Shadow** [comment]
Should this be closed? To me, the corpses that are already there are good enough.
