### ISSUE TITLE
[TCOTD2] Voxels?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#88]
Saw an old discussion about voxelizing some of the sprites - perhaps there's something useful in this pack: https://github.com/fgsfds/Blood-Voxel-Pack

**Comment by Ozymandias81** [comment]
Please no, I am already aware from where I must get voxels, but if we use them for trees, the game will turn a slo-mo experience. You can verify it by checking this [old commit](https://github.com/Realm667/Re-Releases/commit/faf54efffafe550a356923691c7489002adc0651)

**Comment by nashmuhandes** [comment]
No problem - it was just a suggestion... I'm not too particular with this area of development, at any case :)
