### ISSUE TITLE
[TCotD2] About the big spiders boss battle

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#89]
Something about boss encounter with the big spiders doesn't make sense: the only way out of that room is through the vent shaft. Now the shaft is blocked by the cover, which the player can't destroy. However, as soon as the spiders are defeated, the cover is conveniently destroyed by itself. What did happen there? Did the cover just dissolve on its own?

**Comment by nashmuhandes** [comment]
Yeah this is one of those legacy things that kind of just is.

I had the ambitious idea to actually place a wall-based boss on there (like a stationary spider-like abomination) blocking the vent, and the only way through is to kill it. This was waaaay back when I had a lot of time and lots of ideas. This would have, of course, required me to sprite a new boss set - not impossible, but again, I had much more free time back in the day.

Some other ideas:

- have the vent covered by some very, very thick spider webs, that get destroyed when the boss is defeated
- make the vent locked (with a visible padlock), and have the key dropped from the spider boss

The spider boss battle is generally quite meh and definitely should be improved a lot

**Comment by Tormentor667** [comment]
I like the first idea with the spider webs... maybe we can turn the whole room into some kind of a spider room, full of webs, slow movement, just as it got corrupted by spiders. I am open to all of your improvements.

**Comment by Blue-Shadow** [comment]
I'd go for the webs idea, too. But please, no slowing the player down. The player actor isn't that fast to begin with. Its side movement speed is slow. Stepping into that room would pretty much be a death sentence.

**Comment by Tormentor667** [comment]
Good point indeed.

**Comment by nashmuhandes** [comment]
![image](https://user-images.githubusercontent.com/4926156/212494826-2b05c0c0-27d3-42f7-9934-2bfaf25173ae.png)

Spider boss concept, mashed this together in 15 minutes, any thoughts?

**Comment by Tormentor667** [comment]
I love it!

**Comment by nashmuhandes** [comment]
I've added some scripted set pieces where there's some very thick spider webs covering both the nest and the vent. The nest one breaks open when the key is picked up from the billiard table, while the vent one breaks when the boss fight is won.

This room could really use a custom spider boss queen like in my concept, but that will come later

**Comment by Blue-Shadow** [comment]
I'm closing this since the original complaint has been addressed.

**Comment by Tormentor667** [comment]
Reopening it: Can debris be added when the spider webs are destroyed?

**Comment by nashmuhandes** [comment]
Finally added the spider queen. https://github.com/Realm667/Re-Releases/commit/ce7fa78a4656bb7c6f487d9b45716dd39fc390b0

I have decided to do only front-facing sprites for now as it simply takes way too much time and effort to do a full rotation in time for the release. The boss encounter will likely be quite short and it doesn't justify the amount of work I need to put into it.

I can finish the rotations in future if needed, but that's a topic for another time.

**Comment by Tormentor667** [comment]
Having it one-sided is just fine, considering the movement and attack aspect as well as the phyiscal movement possibilities of a spider. I am so okay with this - brilliant work btw!
