### ISSUE TITLE
[TCOTD2] Wall a little too bright

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#91]
This wall appears little too bright:

![Screenshot_Doom_20230112_093550](https://user-images.githubusercontent.com/4287687/212004549-8e4b0f3f-d481-451b-a284-cd18bab17d28.png)

For comparison, here's the wall on the opposite side:

![Screenshot_Doom_20230112_093556](https://user-images.githubusercontent.com/4287687/212004706-fa8808fc-0a21-4a61-9c3b-8d1f6fb50ecf.png)

**Comment by nashmuhandes** [comment]
This had me scratching my head for a while.

So in the `MapSetup` script, at the `// Outside Color` section, it appears to be assigning a color to the woods. The city area, then, are all tagged 0. That explains the color differences.

I'll see what I can do

**Comment by Blue-Shadow** [comment]
You missed a spot.

![Screenshot_Doom_20230113_035229](https://user-images.githubusercontent.com/4287687/212212677-e2bd1e1c-4913-473e-ba6b-faa822187976.png)
