### ISSUE TITLE
[TCOTD2] Window doesn't block sight & attacks

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#93]
This window neither blocks sight nor attacks.

![Screenshot_Doom_20230112_103627](https://user-images.githubusercontent.com/4287687/212007637-f39dcf68-e730-46c6-afeb-5571fd8db75a.png)

**Comment by nashmuhandes** [comment]
Fixed

**Comment by Blue-Shadow** [comment]
While it now blocks attacks, it doesn't block line of sight; the cultist will still attempt to shoot player from inside if he sees him or her from the window.

**Comment by nashmuhandes** [comment]
> While it now blocks attacks, it doesn't block line of sight; the cultist will still attempt to shoot player from inside if he sees him or her from the window.

I deliberately didn't block the LOS - my justification is that the window is translucent. In my testing, this also causes the Cultist to open the door and actually go outside.

I'll leave it up to Torm to make the call for this one

**Comment by Tormentor667** [comment]
I am fine with as it is.l now so this can be closed
