### ISSUE TITLE
[TCOTD2] does motion blur really need to be embedded into this mod?

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#94]
That particular motion blur mod is a famous mod that users could load in after-the-fact, anyway.

Plus, while I am generally a fan of motion blur myself, I am _not_ a fan of how it's done in GZDoom (it's done the crappy way (of copying the image several times then fading them out), not the actual modern-engine way with per-object motion blur, motion vectors and things like that).

GZDoom can never do proper motion blur because it's lacking several graphics features needed to do it properly.

**Comment by Tormentor667** [comment]
It's one of the decisions I made for many of my remasters in general, making the mods available outside the community and incorporating modern features - so, I'd like to actually keep it.

**Comment by nashmuhandes** [comment]
Understood
