### ISSUE TITLE
[TCOTD2] wall torch fire code isn't portal friendly

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#96]

**Comment by Blue-Shadow** [comment]
Maybe it's time to get rid of the sight checks and switch the actor-based flame particles to particle-based... particles.

**Comment by nashmuhandes** [comment]
Yup, lots of overhauls planned in light of recent engine features

**Comment by Tormentor667** [comment]
What's the difference between flame particles and particle particles? :D

**Comment by nashmuhandes** [comment]
Closing this because it's not a problem with GetSightOrRange, but rather the physically-incorrect portal placement
