### ISSUE TITLE
[TCOTD2] rewrite the weather system completely

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#97]

**Comment by Blue-Shadow** [comment]
What's wrong with the current system?

**Comment by nashmuhandes** [comment]
- not portal friendly
- I think I can write to be more performant
- I'd like to support 2 weather types (snow/ash for normal world, blood rain for the other world)
- Just clean it up overall with the current-year knowledge of scripting that I have

**Comment by Tormentor667** [comment]
I am all for the two weather systems - I like it :)

**Comment by nashmuhandes** [comment]
Due to lack of time, I won't be adding the blood rain. Maybe in a future update patch

**Comment by Tormentor667** [comment]
Is it that complicated? I imagine adding a "if" check and then, instead of spawning the regular rain actors simply spawn blood ones.
