### ISSUE TITLE
[TCOTD2] SmallFont is unreadable, consider changing to something clearer

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#98]
My girlfriend was watching me play earlier and she said:

"Yulgar?" (I was playing with an HP bar mod that shows the monster name - it's the Vulgar)

Also she found the various center-printed HUD messages literally unreadable - and the more I look at the font, yeah, I agree.

Should probably use a non-stylized font for SmallFont, something that is clearly readable

**Comment by Blue-Shadow** [comment]
Yes please!

**Comment by Tormentor667** [comment]
I am okay with it as long as it fits the overall style of the mod design.

**Comment by Blue-Shadow** [comment]
I thought I try my hand at making one. Worth it?

![Screenshot_Doom_20230128_130134](https://user-images.githubusercontent.com/4287687/215260339-c08add18-8a7f-491b-b7fb-b9ac14413590.png)

(If the font appears similar to a font you've seen before, then the similarities are entirely coincidental - I made this myself pixel by pixel. I didn't look at any reference materials or base it on an existing font.)

**Comment by nashmuhandes** [comment]
I like it, the silhouette at least - very readable. But I think color-wise it's a little too flat. How about adding some shading? But only very lightly - if the shading contrast is too high, the text would become unreadable again. X)

**Comment by Blue-Shadow** [comment]
Yeah, it's currently only a single solid color. I'll see what Tormentor thinks of the font before I put too much work into it.

**Comment by Tormentor667** [comment]
I like it, this is very well done :) Thsnk you for that!

**Comment by Blue-Shadow** [comment]
I took the easy route and gave it a subtle gradient to make it less flat.

![Screenshot_Doom_20230130_064225](https://user-images.githubusercontent.com/4287687/215383282-fce53805-e387-44f1-ac42-59f55dd1ac42.png)

**Comment by nashmuhandes** [comment]
Looks good!

**Comment by Blue-Shadow** [comment]
[The font is in](https://github.com/Realm667/Re-Releases/commit/d9a35689113a97125ef920841e7611de18308a4a).

**Comment by Tormentor667** [comment]
Thanks!
