### ISSUE TITLE
[TCOTD2] Brain storage monsters alerted eariler than intended

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#99]
The monsters in the brain storage can become aware of the player's presence by hearing the player's gunfire outside the building. This, however, only happens if the player is standing (while also firing guns) in the sectors highlighted in the screenshot below.

![gasdsahh](https://user-images.githubusercontent.com/4287687/212217173-3b4c8f52-cadd-404e-9de3-692c6862fc40.png)

**Comment by nashmuhandes** [comment]
Fixed
